/*
 * (C) Chris Wohlgemuth 2002-2003
 *
 */
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */          
/*
 * If you need another license for your project/product (commercial,
 * noncommercial, whatever) contact me at
 * 
 * http://www.os2world.com/cdwriting
 * http://www.geocities.com/SiliconValley/Sector/5785/
 *
 */

/*
 * CWdisk.idl:
 *
 *
 */

#include <wpdisk.idl>

/*
   CLASS: CWMMDisk

   CLASS HIERARCHY:

       SOMObject
         ÀÄÄ WPObject
               ÀÄÄ WPAbstract
                     ÀÄÄ WPDisk
                           ÀÄÄ CWMMDisk
*/

interface M_CWMMDisk;          

interface CWMMDisk : WPDisk
{

    /*
     * New instance methods for CWDisk:
     *
     */

#ifdef __SOMIDL__
  implementation {

    /*
     * Class Modifiers:
     */

    externalprefix = cwmmdisk_;
    externalstem = cwmmdisk;
    majorversion = 1;
    minorversion = 2;
    filestem = cwmmdisk;           //# specifies the filestem for sc-generated files
    metaclass = M_CWMMDisk;
    dllname = "CWMM.dll";
    callstyle = oidl;

    /*
     * Internal instance variables for CWDisk:
     *
     */

    /*
     * WPDisk methods overridden by CWDisk:
     *
     */

    wpViewObject     :override; 
/*    wpInitData : override;
wpDelete : override;*/
wpFree : override;
wpObjectReady : override;
#ifdef __PRIVATE__

#endif

  }; // implementation
#endif /* __SOMIDL__ */
};


interface M_CWMMDisk : M_WPDisk
{

    /*
     * New class methods for M_CWDisk:
     *
     */


#ifdef __SOMIDL__
  implementation {


    /*
     * Class Modifiers:
     *
     */

    externalprefix = cwmmdiskM_;
    externalstem = cwmmdiskM;
    functionprefix = cwmmdiskM_;
    majorversion = 1;
    minorversion = 2;
    filestem = cwmmdisk;           //# specifies the filestem for sc-generated files
    dllname = "CWMM.dll";
    callstyle = oidl;

    /*
     * Internal class variables
     *
     */

    /*
     * M_WPDisk methods overridden by M_CWDisk:
     *
     */

    wpclsQueryTitle: override;

  };

#endif /* __SOMIDL__ */

};


