
/*
 * This file was generated by the SOM Compiler.
 * FileName: include\cwdib.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 * 
 * CWgif.idl:
 */


#ifndef SOM_CWDIB_h
#define SOM_CWDIB_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef CWDIB
#define CWDIB SOMObject
#endif
#include <cwimage.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPDataFile
    #define M_WPDataFile SOMObject
#endif /* M_WPDataFile */
#ifndef M_WPImageFile
    #define M_WPImageFile SOMObject
#endif /* M_WPImageFile */
#ifndef M_CWImage
    #define M_CWImage SOMObject
#endif /* M_CWImage */
#ifndef M_CWDIB
    #define M_CWDIB SOMObject
#endif /* M_CWDIB */

/*
 * End of user-defined types.
 */

#define CWDIB_MajorVersion 1
#define CWDIB_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define CWDIBNewClass cwdibc
#pragma linkage(cwdibc, system)
#define CWDIBClassData cwdibd
#define CWDIBCClassData cwdibx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <cwdib.h>
/*--------------Migration------------*/
#define CWDIB_classObj CWDIBClassData.classObject
#define _CWDIB CWDIB_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK CWDIBNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(CWDIBNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct CWDIBClassDataStructure {
	SOMClass *classObject;
} SOMDLINK CWDIBClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct CWDIBCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK CWDIBCClassData;

/*
 * New and Renew macros for CWDIB
 */
#define CWDIBNew() \
   (_somNew(_CWDIB ? _CWDIB : CWDIBNewClass(CWDIB_MajorVersion, CWDIB_MinorVersion)))
#define CWDIBRenew(buf) \
   (_somRenew(_CWDIB ? _CWDIB : CWDIBNewClass(CWDIB_MajorVersion, CWDIB_MinorVersion), buf))
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define CWDIB_cwmmAddImageInformationPage CWImage_cwmmAddImageInformationPage
#define CWDIB_wpQueryBitmapHandle WPImageFile_wpQueryBitmapHandle
#define CWDIB_wpQueryBitmapInfoHeader WPImageFile_wpQueryBitmapInfoHeader
#define CWDIB_wpQueryBitmapData WPImageFile_wpQueryBitmapData
#define CWDIB_wpSetBitmapData WPImageFile_wpSetBitmapData
#define CWDIB_wpReadImageFile WPImageFile_wpReadImageFile
#define CWDIB_wpWriteImageFile WPImageFile_wpWriteImageFile
#define CWDIB_wpAddFileTypePage WPDataFile_wpAddFileTypePage
#define CWDIB_wpPrintMetaFile WPDataFile_wpPrintMetaFile
#define CWDIB_wpPrintPifFile WPDataFile_wpPrintPifFile
#define CWDIB_wpPrintPrinterSpecificFile WPDataFile_wpPrintPrinterSpecificFile
#define CWDIB_wpPrintUnknownFile WPDataFile_wpPrintUnknownFile
#define CWDIB_wpQueryAssociatedProgram WPDataFile_wpQueryAssociatedProgram
#define CWDIB_wpSetAssociatedFileIcon WPDataFile_wpSetAssociatedFileIcon
#define CWDIB_wpQueryAssociatedFileIcon WPDataFile_wpQueryAssociatedFileIcon
#define CWDIB_wpSetRealName WPFileSystem_wpSetRealName
#define CWDIB_wpSetType WPFileSystem_wpSetType
#define CWDIB_wpQueryType WPFileSystem_wpQueryType
#define CWDIB_wpSetAttr WPFileSystem_wpSetAttr
#define CWDIB_wpQueryAttr WPFileSystem_wpQueryAttr
#define CWDIB_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define CWDIB_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define CWDIB_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define CWDIB_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define CWDIB_wpQueryCreation WPFileSystem_wpQueryCreation
#define CWDIB_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define CWDIB_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define CWDIB_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define CWDIB_wpQueryEASize WPFileSystem_wpQueryEASize
#define CWDIB_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define CWDIB_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define CWDIB_wpRefresh WPFileSystem_wpRefresh
#define CWDIB_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define CWDIB_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define CWDIB_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define CWDIB_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define CWDIB_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define CWDIB_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define CWDIB_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define CWDIB_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define CWDIB_wpQueryRealName WPFileSystem_wpQueryRealName
#define CWDIB_wpQueryFilename WPFileSystem_wpQueryFilename
#define CWDIB_wpQueryDisk WPFileSystem_wpQueryDisk
#define CWDIB_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define CWDIB_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define CWDIB_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define CWDIB_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define CWDIB_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define CWDIB_wpAddSettingsPages WPObject_wpAddSettingsPages
#define CWDIB_wpAddToObjUseList WPObject_wpAddToObjUseList
#define CWDIB_wpAllocMem WPObject_wpAllocMem
#define CWDIB_wpAppendObject WPObject_wpAppendObject
#define CWDIB_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define CWDIB_wpClose WPObject_wpClose
#define CWDIB_wpCnrInsertObject WPObject_wpCnrInsertObject
#define CWDIB_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define CWDIB_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define CWDIB_wpConfirmDelete WPObject_wpConfirmDelete
#define CWDIB_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define CWDIB_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define CWDIB_wpCopyObject WPObject_wpCopyObject
#define CWDIB_wpCreateAnother WPObject_wpCreateAnother
#define CWDIB_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define CWDIB_wpCreateShadowObject WPObject_wpCreateShadowObject
#define CWDIB_wpDelete WPObject_wpDelete
#define CWDIB_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define CWDIB_wpDisplayHelp WPObject_wpDisplayHelp
#define CWDIB_wpDisplayMenu WPObject_wpDisplayMenu
#define CWDIB_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define CWDIB_wpDraggedOverObject WPObject_wpDraggedOverObject
#define CWDIB_wpDragOver WPObject_wpDragOver
#define CWDIB_wpDrop WPObject_wpDrop
#define CWDIB_wpDroppedOnObject WPObject_wpDroppedOnObject
#define CWDIB_wpEndConversation WPObject_wpEndConversation
#define CWDIB_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define CWDIB_wpFindUseItem WPObject_wpFindUseItem
#define CWDIB_wpFormatDragItem WPObject_wpFormatDragItem
#define CWDIB_wpFree WPObject_wpFree
#define CWDIB_wpFreeMem WPObject_wpFreeMem
#define CWDIB_wpHide WPObject_wpHide
#define CWDIB_wpInitData WPObject_wpInitData
#define CWDIB_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define CWDIB_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define CWDIB_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define CWDIB_wpMenuItemSelected WPObject_wpMenuItemSelected
#define CWDIB_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define CWDIB_wpMoveObject WPObject_wpMoveObject
#define CWDIB_wpOpen WPObject_wpOpen
#define CWDIB_wpPrintObject WPObject_wpPrintObject
#define CWDIB_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define CWDIB_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define CWDIB_wpQueryConfirmations WPObject_wpQueryConfirmations
#define CWDIB_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define CWDIB_wpQueryDefaultView WPObject_wpQueryDefaultView
#define CWDIB_wpQueryDetailsData WPObject_wpQueryDetailsData
#define CWDIB_wpQueryError WPObject_wpQueryError
#define CWDIB_wpSetFolder WPObject_wpSetFolder
#define CWDIB_wpQueryFolder WPObject_wpQueryFolder
#define CWDIB_wpQueryIcon WPObject_wpQueryIcon
#define CWDIB_wpQueryIconData WPObject_wpQueryIconData
#define CWDIB_wpQueryMinWindow WPObject_wpQueryMinWindow
#define CWDIB_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define CWDIB_wpQueryStyle WPObject_wpQueryStyle
#define CWDIB_wpSetTaskRec WPObject_wpSetTaskRec
#define CWDIB_wpFindTaskRec WPObject_wpFindTaskRec
#define CWDIB_wpQueryTitle WPObject_wpQueryTitle
#define CWDIB_wpRegisterView WPObject_wpRegisterView
#define CWDIB_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define CWDIB_wpRender WPObject_wpRender
#define CWDIB_wpRenderComplete WPObject_wpRenderComplete
#define CWDIB_wpReplaceObject WPObject_wpReplaceObject
#define CWDIB_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define CWDIB_wpRestore WPObject_wpRestore
#define CWDIB_wpRestoreData WPObject_wpRestoreData
#define CWDIB_wpRestoreLong WPObject_wpRestoreLong
#define CWDIB_wpRestoreState WPObject_wpRestoreState
#define CWDIB_wpRestoreString WPObject_wpRestoreString
#define CWDIB_wpSaveData WPObject_wpSaveData
#define CWDIB_wpSaveImmediate WPObject_wpSaveImmediate
#define CWDIB_wpSaveDeferred WPObject_wpSaveDeferred
#define CWDIB_wpSaveLong WPObject_wpSaveLong
#define CWDIB_wpSaveState WPObject_wpSaveState
#define CWDIB_wpSaveString WPObject_wpSaveString
#define CWDIB_wpScanSetupString WPObject_wpScanSetupString
#define CWDIB_wpSetConcurrentView WPObject_wpSetConcurrentView
#define CWDIB_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define CWDIB_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define CWDIB_wpSetDefaultView WPObject_wpSetDefaultView
#define CWDIB_wpSetError WPObject_wpSetError
#define CWDIB_wpSetIconHandle WPObject_wpSetIconHandle
#define CWDIB_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define CWDIB_wpSetupOnce WPObject_wpSetupOnce
#define CWDIB_wpSetIcon WPObject_wpSetIcon
#define CWDIB_wpSetIconData WPObject_wpSetIconData
#define CWDIB_wpSetMinWindow WPObject_wpSetMinWindow
#define CWDIB_wpSetStyle WPObject_wpSetStyle
#define CWDIB_wpModifyStyle WPObject_wpModifyStyle
#define CWDIB_wpSetTitle WPObject_wpSetTitle
#define CWDIB_wpSetup WPObject_wpSetup
#define CWDIB_wpSwitchTo WPObject_wpSwitchTo
#define CWDIB_wpUnInitData WPObject_wpUnInitData
#define CWDIB_wpViewObject WPObject_wpViewObject
#define CWDIB_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define CWDIB_wpQueryHandle WPObject_wpQueryHandle
#define CWDIB_wpUnlockObject WPObject_wpUnlockObject
#define CWDIB_wpObjectReady WPObject_wpObjectReady
#define CWDIB_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define CWDIB_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define CWDIB_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define CWDIB_wpIsDeleteable WPObject_wpIsDeleteable
#define CWDIB_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define CWDIB_wpSetObjectID WPObject_wpSetObjectID
#define CWDIB_wpQueryObjectID WPObject_wpQueryObjectID
#define CWDIB_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define CWDIB_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define CWDIB_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define CWDIB_wpFindViewItem WPObject_wpFindViewItem
#define CWDIB_wpLockObject WPObject_wpLockObject
#define CWDIB_wpIsLocked WPObject_wpIsLocked
#define CWDIB_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define CWDIB_wpWaitForClose WPObject_wpWaitForClose
#define CWDIB_somDefaultInit SOMObject_somDefaultInit
#define CWDIB_somDestruct SOMObject_somDestruct
#define CWDIB_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define CWDIB_somDefaultAssign SOMObject_somDefaultAssign
#define CWDIB_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define CWDIB_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define CWDIB_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define CWDIB_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define CWDIB_somDefaultVAssign SOMObject_somDefaultVAssign
#define CWDIB_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define CWDIB_somInit SOMObject_somInit
#define CWDIB_somFree SOMObject_somFree
#define CWDIB_somUninit SOMObject_somUninit
#define CWDIB_somGetClass SOMObject_somGetClass
#define CWDIB_somGetClassName SOMObject_somGetClassName
#define CWDIB_somGetSize SOMObject_somGetSize
#define CWDIB_somIsA SOMObject_somIsA
#define CWDIB_somIsInstanceOf SOMObject_somIsInstanceOf
#define CWDIB_somRespondsTo SOMObject_somRespondsTo
#define CWDIB_somDispatch SOMObject_somDispatch
#define CWDIB_somClassDispatch SOMObject_somClassDispatch
#define CWDIB_somCastObj SOMObject_somCastObj
#define CWDIB_somResetObj SOMObject_somResetObj
#define CWDIB_somDispatchV SOMObject_somDispatchV
#define CWDIB_somDispatchL SOMObject_somDispatchL
#define CWDIB_somDispatchA SOMObject_somDispatchA
#define CWDIB_somDispatchD SOMObject_somDispatchD
#define CWDIB_somPrintSelf SOMObject_somPrintSelf
#define CWDIB_somDumpSelf SOMObject_somDumpSelf
#define CWDIB_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_CWDIB_h */

#ifndef SOM_M_CWDIB_h
#define SOM_M_CWDIB_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_CWDIB
#define M_CWDIB SOMObject
#endif
#include <cwimage.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_CWDIB_MajorVersion 1
#define M_CWDIB_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_CWDIBNewClass cwdibMc
#pragma linkage(cwdibMc, system)
#define M_CWDIBClassData cwdibMd
#define M_CWDIBCClassData cwdibMx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_CWDIB_classObj M_CWDIBClassData.classObject
#define _M_CWDIB M_CWDIB_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_CWDIBNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_CWDIBNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_CWDIBClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_CWDIBClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_CWDIBCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_CWDIBCClassData;

/*
 * New and Renew macros for M_CWDIB
 */
#define M_CWDIBNew() \
   (_somNew(_M_CWDIB ? _M_CWDIB : M_CWDIBNewClass(M_CWDIB_MajorVersion, M_CWDIB_MinorVersion)))
#define M_CWDIBRenew(buf) \
   (_somRenew(_M_CWDIB ? _M_CWDIB : M_CWDIBNewClass(M_CWDIB_MajorVersion, M_CWDIB_MinorVersion), buf))

/*
 * Override method: wpclsQueryInstanceType
 */
#define M_CWDIB_wpclsQueryInstanceType(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceType(somSelf)

/*
 * Override method: wpclsQueryInstanceFilter
 */
#define M_CWDIB_wpclsQueryInstanceFilter(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceFilter(somSelf)

/*
 * Override method: wpclsQueryDefaultHelp
 */
#define M_CWDIB_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary) \
	M_WPObject_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary)

/*
 * Override method: wpclsQueryStyle
 */
#define M_CWDIB_wpclsQueryStyle(somSelf) \
	M_WPObject_wpclsQueryStyle(somSelf)

/*
 * Override method: wpclsQueryTitle
 */
#define M_CWDIB_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_CWDIB_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_CWDIB_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_CWDIB_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_CWDIB_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_CWDIB_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_CWDIB_wpclsInitData M_WPObject_wpclsInitData
#define M_CWDIB_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_CWDIB_wpclsNew M_WPObject_wpclsNew
#define M_CWDIB_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_CWDIB_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_CWDIB_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_CWDIB_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_CWDIB_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_CWDIB_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_CWDIB_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_CWDIB_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_CWDIB_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_CWDIB_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_CWDIB_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_CWDIB_wpclsSetError M_WPObject_wpclsSetError
#define M_CWDIB_wpclsQueryError M_WPObject_wpclsQueryError
#define M_CWDIB_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_CWDIB_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_CWDIB_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_CWDIB_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_CWDIB_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_CWDIB_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_CWDIB_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_CWDIB_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_CWDIB_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_CWDIB_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_CWDIB_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_CWDIB_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_CWDIB__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_CWDIB__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_CWDIB__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_CWDIB__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_CWDIB_somNew SOMClass_somNew
#define M_CWDIB_somNewNoInit SOMClass_somNewNoInit
#define M_CWDIB_somRenew SOMClass_somRenew
#define M_CWDIB_somRenewNoInit SOMClass_somRenewNoInit
#define M_CWDIB_somRenewNoZero SOMClass_somRenewNoZero
#define M_CWDIB_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_CWDIB_somAllocate SOMClass_somAllocate
#define M_CWDIB_somDeallocate SOMClass_somDeallocate
#define M_CWDIB__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_CWDIB__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_CWDIB_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_CWDIB_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_CWDIB_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_CWDIB_somInitClass SOMClass_somInitClass
#define M_CWDIB_somInitMIClass SOMClass_somInitMIClass
#define M_CWDIB_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_CWDIB_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_CWDIB_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_CWDIB_somClassReady SOMClass_somClassReady
#define M_CWDIB_somGetApplyStub SOMClass_somGetApplyStub
#define M_CWDIB_somGetClassData SOMClass_somGetClassData
#define M_CWDIB_somSetClassData SOMClass_somSetClassData
#define M_CWDIB_somGetClassMtab SOMClass_somGetClassMtab
#define M_CWDIB_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_CWDIB_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_CWDIB_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_CWDIB_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_CWDIB_somGetMemberToken SOMClass_somGetMemberToken
#define M_CWDIB_somGetMethodData SOMClass_somGetMethodData
#define M_CWDIB_somGetRdStub SOMClass_somGetRdStub
#define M_CWDIB_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_CWDIB_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_CWDIB_somGetMethodToken SOMClass_somGetMethodToken
#define M_CWDIB_somGetName SOMClass_somGetName
#define M_CWDIB_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_CWDIB_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_CWDIB_somGetNumMethods SOMClass_somGetNumMethods
#define M_CWDIB_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_CWDIB_somGetParent SOMClass_somGetParent
#define M_CWDIB_somGetParents SOMClass_somGetParents
#define M_CWDIB_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_CWDIB_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_CWDIB_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_CWDIB_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_CWDIB_somFindMethod SOMClass_somFindMethod
#define M_CWDIB_somFindMethodOk SOMClass_somFindMethodOk
#define M_CWDIB_somFindSMethod SOMClass_somFindSMethod
#define M_CWDIB_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_CWDIB_somLookupMethod SOMClass_somLookupMethod
#define M_CWDIB_somCheckVersion SOMClass_somCheckVersion
#define M_CWDIB_somDescendedFrom SOMClass_somDescendedFrom
#define M_CWDIB_somSupportsMethod SOMClass_somSupportsMethod
#define M_CWDIB_somDefinedMethod SOMClass_somDefinedMethod
#define M_CWDIB_somOverrideMtab SOMClass_somOverrideMtab
#define M_CWDIB_somDefaultInit SOMObject_somDefaultInit
#define M_CWDIB_somDestruct SOMObject_somDestruct
#define M_CWDIB_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_CWDIB_somDefaultAssign SOMObject_somDefaultAssign
#define M_CWDIB_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_CWDIB_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_CWDIB_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_CWDIB_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_CWDIB_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_CWDIB_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_CWDIB_somInit SOMObject_somInit
#define M_CWDIB_somFree SOMObject_somFree
#define M_CWDIB_somUninit SOMObject_somUninit
#define M_CWDIB_somGetClass SOMObject_somGetClass
#define M_CWDIB_somGetClassName SOMObject_somGetClassName
#define M_CWDIB_somGetSize SOMObject_somGetSize
#define M_CWDIB_somIsA SOMObject_somIsA
#define M_CWDIB_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_CWDIB_somRespondsTo SOMObject_somRespondsTo
#define M_CWDIB_somDispatch SOMObject_somDispatch
#define M_CWDIB_somClassDispatch SOMObject_somClassDispatch
#define M_CWDIB_somCastObj SOMObject_somCastObj
#define M_CWDIB_somResetObj SOMObject_somResetObj
#define M_CWDIB_somDispatchV SOMObject_somDispatchV
#define M_CWDIB_somDispatchL SOMObject_somDispatchL
#define M_CWDIB_somDispatchA SOMObject_somDispatchA
#define M_CWDIB_somDispatchD SOMObject_somDispatchD
#define M_CWDIB_somPrintSelf SOMObject_somPrintSelf
#define M_CWDIB_somDumpSelf SOMObject_somDumpSelf
#define M_CWDIB_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_CWDIB_h */
