
/*
 * This file was generated by the SOM Compiler.
 * FileName: include\cwmmotion.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 * 
 * CWgif.idl:
 */


#ifndef SOM_CWMMotion_h
#define SOM_CWMMotion_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef CWMMotion
#define CWMMotion SOMObject
#endif
#include <cwimage.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPDataFile
    #define M_WPDataFile SOMObject
#endif /* M_WPDataFile */
#ifndef M_WPImageFile
    #define M_WPImageFile SOMObject
#endif /* M_WPImageFile */
#ifndef M_CWImage
    #define M_CWImage SOMObject
#endif /* M_CWImage */
#ifndef M_CWMMotion
    #define M_CWMMotion SOMObject
#endif /* M_CWMMotion */

/*
 * End of user-defined types.
 */

#define CWMMotion_MajorVersion 1
#define CWMMotion_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define CWMMotionNewClass cwmmotionc
#pragma linkage(cwmmotionc, system)
#define CWMMotionClassData cwmmotiond
#define CWMMotionCClassData cwmmotionx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <cwmmotion.h>
/*--------------Migration------------*/
#define CWMMotion_classObj CWMMotionClassData.classObject
#define _CWMMotion CWMMotion_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK CWMMotionNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(CWMMotionNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct CWMMotionClassDataStructure {
	SOMClass *classObject;
} SOMDLINK CWMMotionClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct CWMMotionCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK CWMMotionCClassData;

/*
 * New and Renew macros for CWMMotion
 */
#define CWMMotionNew() \
   (_somNew(_CWMMotion ? _CWMMotion : CWMMotionNewClass(CWMMotion_MajorVersion, CWMMotion_MinorVersion)))
#define CWMMotionRenew(buf) \
   (_somRenew(_CWMMotion ? _CWMMotion : CWMMotionNewClass(CWMMotion_MajorVersion, CWMMotion_MinorVersion), buf))
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define CWMMotion_cwmmAddImageInformationPage CWImage_cwmmAddImageInformationPage
#define CWMMotion_wpQueryBitmapHandle WPImageFile_wpQueryBitmapHandle
#define CWMMotion_wpQueryBitmapInfoHeader WPImageFile_wpQueryBitmapInfoHeader
#define CWMMotion_wpQueryBitmapData WPImageFile_wpQueryBitmapData
#define CWMMotion_wpSetBitmapData WPImageFile_wpSetBitmapData
#define CWMMotion_wpReadImageFile WPImageFile_wpReadImageFile
#define CWMMotion_wpWriteImageFile WPImageFile_wpWriteImageFile
#define CWMMotion_wpAddFileTypePage WPDataFile_wpAddFileTypePage
#define CWMMotion_wpPrintMetaFile WPDataFile_wpPrintMetaFile
#define CWMMotion_wpPrintPifFile WPDataFile_wpPrintPifFile
#define CWMMotion_wpPrintPrinterSpecificFile WPDataFile_wpPrintPrinterSpecificFile
#define CWMMotion_wpPrintUnknownFile WPDataFile_wpPrintUnknownFile
#define CWMMotion_wpQueryAssociatedProgram WPDataFile_wpQueryAssociatedProgram
#define CWMMotion_wpSetAssociatedFileIcon WPDataFile_wpSetAssociatedFileIcon
#define CWMMotion_wpQueryAssociatedFileIcon WPDataFile_wpQueryAssociatedFileIcon
#define CWMMotion_wpSetRealName WPFileSystem_wpSetRealName
#define CWMMotion_wpSetType WPFileSystem_wpSetType
#define CWMMotion_wpQueryType WPFileSystem_wpQueryType
#define CWMMotion_wpSetAttr WPFileSystem_wpSetAttr
#define CWMMotion_wpQueryAttr WPFileSystem_wpQueryAttr
#define CWMMotion_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define CWMMotion_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define CWMMotion_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define CWMMotion_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define CWMMotion_wpQueryCreation WPFileSystem_wpQueryCreation
#define CWMMotion_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define CWMMotion_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define CWMMotion_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define CWMMotion_wpQueryEASize WPFileSystem_wpQueryEASize
#define CWMMotion_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define CWMMotion_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define CWMMotion_wpRefresh WPFileSystem_wpRefresh
#define CWMMotion_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define CWMMotion_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define CWMMotion_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define CWMMotion_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define CWMMotion_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define CWMMotion_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define CWMMotion_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define CWMMotion_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define CWMMotion_wpQueryRealName WPFileSystem_wpQueryRealName
#define CWMMotion_wpQueryFilename WPFileSystem_wpQueryFilename
#define CWMMotion_wpQueryDisk WPFileSystem_wpQueryDisk
#define CWMMotion_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define CWMMotion_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define CWMMotion_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define CWMMotion_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define CWMMotion_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define CWMMotion_wpAddSettingsPages WPObject_wpAddSettingsPages
#define CWMMotion_wpAddToObjUseList WPObject_wpAddToObjUseList
#define CWMMotion_wpAllocMem WPObject_wpAllocMem
#define CWMMotion_wpAppendObject WPObject_wpAppendObject
#define CWMMotion_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define CWMMotion_wpClose WPObject_wpClose
#define CWMMotion_wpCnrInsertObject WPObject_wpCnrInsertObject
#define CWMMotion_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define CWMMotion_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define CWMMotion_wpConfirmDelete WPObject_wpConfirmDelete
#define CWMMotion_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define CWMMotion_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define CWMMotion_wpCopyObject WPObject_wpCopyObject
#define CWMMotion_wpCreateAnother WPObject_wpCreateAnother
#define CWMMotion_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define CWMMotion_wpCreateShadowObject WPObject_wpCreateShadowObject
#define CWMMotion_wpDelete WPObject_wpDelete
#define CWMMotion_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define CWMMotion_wpDisplayHelp WPObject_wpDisplayHelp
#define CWMMotion_wpDisplayMenu WPObject_wpDisplayMenu
#define CWMMotion_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define CWMMotion_wpDraggedOverObject WPObject_wpDraggedOverObject
#define CWMMotion_wpDragOver WPObject_wpDragOver
#define CWMMotion_wpDrop WPObject_wpDrop
#define CWMMotion_wpDroppedOnObject WPObject_wpDroppedOnObject
#define CWMMotion_wpEndConversation WPObject_wpEndConversation
#define CWMMotion_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define CWMMotion_wpFindUseItem WPObject_wpFindUseItem
#define CWMMotion_wpFormatDragItem WPObject_wpFormatDragItem
#define CWMMotion_wpFree WPObject_wpFree
#define CWMMotion_wpFreeMem WPObject_wpFreeMem
#define CWMMotion_wpHide WPObject_wpHide
#define CWMMotion_wpInitData WPObject_wpInitData
#define CWMMotion_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define CWMMotion_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define CWMMotion_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define CWMMotion_wpMenuItemSelected WPObject_wpMenuItemSelected
#define CWMMotion_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define CWMMotion_wpMoveObject WPObject_wpMoveObject
#define CWMMotion_wpOpen WPObject_wpOpen
#define CWMMotion_wpPrintObject WPObject_wpPrintObject
#define CWMMotion_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define CWMMotion_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define CWMMotion_wpQueryConfirmations WPObject_wpQueryConfirmations
#define CWMMotion_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define CWMMotion_wpQueryDefaultView WPObject_wpQueryDefaultView
#define CWMMotion_wpQueryDetailsData WPObject_wpQueryDetailsData
#define CWMMotion_wpQueryError WPObject_wpQueryError
#define CWMMotion_wpSetFolder WPObject_wpSetFolder
#define CWMMotion_wpQueryFolder WPObject_wpQueryFolder
#define CWMMotion_wpQueryIcon WPObject_wpQueryIcon
#define CWMMotion_wpQueryIconData WPObject_wpQueryIconData
#define CWMMotion_wpQueryMinWindow WPObject_wpQueryMinWindow
#define CWMMotion_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define CWMMotion_wpQueryStyle WPObject_wpQueryStyle
#define CWMMotion_wpSetTaskRec WPObject_wpSetTaskRec
#define CWMMotion_wpFindTaskRec WPObject_wpFindTaskRec
#define CWMMotion_wpQueryTitle WPObject_wpQueryTitle
#define CWMMotion_wpRegisterView WPObject_wpRegisterView
#define CWMMotion_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define CWMMotion_wpRender WPObject_wpRender
#define CWMMotion_wpRenderComplete WPObject_wpRenderComplete
#define CWMMotion_wpReplaceObject WPObject_wpReplaceObject
#define CWMMotion_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define CWMMotion_wpRestore WPObject_wpRestore
#define CWMMotion_wpRestoreData WPObject_wpRestoreData
#define CWMMotion_wpRestoreLong WPObject_wpRestoreLong
#define CWMMotion_wpRestoreState WPObject_wpRestoreState
#define CWMMotion_wpRestoreString WPObject_wpRestoreString
#define CWMMotion_wpSaveData WPObject_wpSaveData
#define CWMMotion_wpSaveImmediate WPObject_wpSaveImmediate
#define CWMMotion_wpSaveDeferred WPObject_wpSaveDeferred
#define CWMMotion_wpSaveLong WPObject_wpSaveLong
#define CWMMotion_wpSaveState WPObject_wpSaveState
#define CWMMotion_wpSaveString WPObject_wpSaveString
#define CWMMotion_wpScanSetupString WPObject_wpScanSetupString
#define CWMMotion_wpSetConcurrentView WPObject_wpSetConcurrentView
#define CWMMotion_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define CWMMotion_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define CWMMotion_wpSetDefaultView WPObject_wpSetDefaultView
#define CWMMotion_wpSetError WPObject_wpSetError
#define CWMMotion_wpSetIconHandle WPObject_wpSetIconHandle
#define CWMMotion_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define CWMMotion_wpSetupOnce WPObject_wpSetupOnce
#define CWMMotion_wpSetIcon WPObject_wpSetIcon
#define CWMMotion_wpSetIconData WPObject_wpSetIconData
#define CWMMotion_wpSetMinWindow WPObject_wpSetMinWindow
#define CWMMotion_wpSetStyle WPObject_wpSetStyle
#define CWMMotion_wpModifyStyle WPObject_wpModifyStyle
#define CWMMotion_wpSetTitle WPObject_wpSetTitle
#define CWMMotion_wpSetup WPObject_wpSetup
#define CWMMotion_wpSwitchTo WPObject_wpSwitchTo
#define CWMMotion_wpUnInitData WPObject_wpUnInitData
#define CWMMotion_wpViewObject WPObject_wpViewObject
#define CWMMotion_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define CWMMotion_wpQueryHandle WPObject_wpQueryHandle
#define CWMMotion_wpUnlockObject WPObject_wpUnlockObject
#define CWMMotion_wpObjectReady WPObject_wpObjectReady
#define CWMMotion_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define CWMMotion_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define CWMMotion_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define CWMMotion_wpIsDeleteable WPObject_wpIsDeleteable
#define CWMMotion_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define CWMMotion_wpSetObjectID WPObject_wpSetObjectID
#define CWMMotion_wpQueryObjectID WPObject_wpQueryObjectID
#define CWMMotion_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define CWMMotion_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define CWMMotion_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define CWMMotion_wpFindViewItem WPObject_wpFindViewItem
#define CWMMotion_wpLockObject WPObject_wpLockObject
#define CWMMotion_wpIsLocked WPObject_wpIsLocked
#define CWMMotion_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define CWMMotion_wpWaitForClose WPObject_wpWaitForClose
#define CWMMotion_somDefaultInit SOMObject_somDefaultInit
#define CWMMotion_somDestruct SOMObject_somDestruct
#define CWMMotion_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define CWMMotion_somDefaultAssign SOMObject_somDefaultAssign
#define CWMMotion_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define CWMMotion_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define CWMMotion_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define CWMMotion_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define CWMMotion_somDefaultVAssign SOMObject_somDefaultVAssign
#define CWMMotion_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define CWMMotion_somInit SOMObject_somInit
#define CWMMotion_somFree SOMObject_somFree
#define CWMMotion_somUninit SOMObject_somUninit
#define CWMMotion_somGetClass SOMObject_somGetClass
#define CWMMotion_somGetClassName SOMObject_somGetClassName
#define CWMMotion_somGetSize SOMObject_somGetSize
#define CWMMotion_somIsA SOMObject_somIsA
#define CWMMotion_somIsInstanceOf SOMObject_somIsInstanceOf
#define CWMMotion_somRespondsTo SOMObject_somRespondsTo
#define CWMMotion_somDispatch SOMObject_somDispatch
#define CWMMotion_somClassDispatch SOMObject_somClassDispatch
#define CWMMotion_somCastObj SOMObject_somCastObj
#define CWMMotion_somResetObj SOMObject_somResetObj
#define CWMMotion_somDispatchV SOMObject_somDispatchV
#define CWMMotion_somDispatchL SOMObject_somDispatchL
#define CWMMotion_somDispatchA SOMObject_somDispatchA
#define CWMMotion_somDispatchD SOMObject_somDispatchD
#define CWMMotion_somPrintSelf SOMObject_somPrintSelf
#define CWMMotion_somDumpSelf SOMObject_somDumpSelf
#define CWMMotion_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_CWMMotion_h */

#ifndef SOM_M_CWMMotion_h
#define SOM_M_CWMMotion_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_CWMMotion
#define M_CWMMotion SOMObject
#endif
#include <cwimage.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_CWMMotion_MajorVersion 1
#define M_CWMMotion_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_CWMMotionNewClass cwmmotionMc
#pragma linkage(cwmmotionMc, system)
#define M_CWMMotionClassData cwmmotionMd
#define M_CWMMotionCClassData cwmmotionMx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_CWMMotion_classObj M_CWMMotionClassData.classObject
#define _M_CWMMotion M_CWMMotion_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_CWMMotionNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_CWMMotionNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_CWMMotionClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_CWMMotionClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_CWMMotionCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_CWMMotionCClassData;

/*
 * New and Renew macros for M_CWMMotion
 */
#define M_CWMMotionNew() \
   (_somNew(_M_CWMMotion ? _M_CWMMotion : M_CWMMotionNewClass(M_CWMMotion_MajorVersion, M_CWMMotion_MinorVersion)))
#define M_CWMMotionRenew(buf) \
   (_somRenew(_M_CWMMotion ? _M_CWMMotion : M_CWMMotionNewClass(M_CWMMotion_MajorVersion, M_CWMMotion_MinorVersion), buf))

/*
 * Override method: wpclsQueryInstanceType
 */
#define M_CWMMotion_wpclsQueryInstanceType(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceType(somSelf)

/*
 * Override method: wpclsQueryInstanceFilter
 */
#define M_CWMMotion_wpclsQueryInstanceFilter(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceFilter(somSelf)

/*
 * Override method: wpclsQueryDefaultHelp
 */
#define M_CWMMotion_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary) \
	M_WPObject_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary)

/*
 * Override method: wpclsQueryStyle
 */
#define M_CWMMotion_wpclsQueryStyle(somSelf) \
	M_WPObject_wpclsQueryStyle(somSelf)

/*
 * Override method: wpclsQueryTitle
 */
#define M_CWMMotion_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_CWMMotion_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_CWMMotion_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_CWMMotion_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_CWMMotion_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_CWMMotion_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_CWMMotion_wpclsInitData M_WPObject_wpclsInitData
#define M_CWMMotion_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_CWMMotion_wpclsNew M_WPObject_wpclsNew
#define M_CWMMotion_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_CWMMotion_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_CWMMotion_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_CWMMotion_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_CWMMotion_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_CWMMotion_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_CWMMotion_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_CWMMotion_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_CWMMotion_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_CWMMotion_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_CWMMotion_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_CWMMotion_wpclsSetError M_WPObject_wpclsSetError
#define M_CWMMotion_wpclsQueryError M_WPObject_wpclsQueryError
#define M_CWMMotion_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_CWMMotion_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_CWMMotion_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_CWMMotion_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_CWMMotion_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_CWMMotion_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_CWMMotion_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_CWMMotion_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_CWMMotion_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_CWMMotion_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_CWMMotion_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_CWMMotion_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_CWMMotion__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_CWMMotion__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_CWMMotion__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_CWMMotion__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_CWMMotion_somNew SOMClass_somNew
#define M_CWMMotion_somNewNoInit SOMClass_somNewNoInit
#define M_CWMMotion_somRenew SOMClass_somRenew
#define M_CWMMotion_somRenewNoInit SOMClass_somRenewNoInit
#define M_CWMMotion_somRenewNoZero SOMClass_somRenewNoZero
#define M_CWMMotion_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_CWMMotion_somAllocate SOMClass_somAllocate
#define M_CWMMotion_somDeallocate SOMClass_somDeallocate
#define M_CWMMotion__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_CWMMotion__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_CWMMotion_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_CWMMotion_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_CWMMotion_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_CWMMotion_somInitClass SOMClass_somInitClass
#define M_CWMMotion_somInitMIClass SOMClass_somInitMIClass
#define M_CWMMotion_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_CWMMotion_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_CWMMotion_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_CWMMotion_somClassReady SOMClass_somClassReady
#define M_CWMMotion_somGetApplyStub SOMClass_somGetApplyStub
#define M_CWMMotion_somGetClassData SOMClass_somGetClassData
#define M_CWMMotion_somSetClassData SOMClass_somSetClassData
#define M_CWMMotion_somGetClassMtab SOMClass_somGetClassMtab
#define M_CWMMotion_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_CWMMotion_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_CWMMotion_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_CWMMotion_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_CWMMotion_somGetMemberToken SOMClass_somGetMemberToken
#define M_CWMMotion_somGetMethodData SOMClass_somGetMethodData
#define M_CWMMotion_somGetRdStub SOMClass_somGetRdStub
#define M_CWMMotion_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_CWMMotion_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_CWMMotion_somGetMethodToken SOMClass_somGetMethodToken
#define M_CWMMotion_somGetName SOMClass_somGetName
#define M_CWMMotion_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_CWMMotion_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_CWMMotion_somGetNumMethods SOMClass_somGetNumMethods
#define M_CWMMotion_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_CWMMotion_somGetParent SOMClass_somGetParent
#define M_CWMMotion_somGetParents SOMClass_somGetParents
#define M_CWMMotion_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_CWMMotion_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_CWMMotion_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_CWMMotion_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_CWMMotion_somFindMethod SOMClass_somFindMethod
#define M_CWMMotion_somFindMethodOk SOMClass_somFindMethodOk
#define M_CWMMotion_somFindSMethod SOMClass_somFindSMethod
#define M_CWMMotion_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_CWMMotion_somLookupMethod SOMClass_somLookupMethod
#define M_CWMMotion_somCheckVersion SOMClass_somCheckVersion
#define M_CWMMotion_somDescendedFrom SOMClass_somDescendedFrom
#define M_CWMMotion_somSupportsMethod SOMClass_somSupportsMethod
#define M_CWMMotion_somDefinedMethod SOMClass_somDefinedMethod
#define M_CWMMotion_somOverrideMtab SOMClass_somOverrideMtab
#define M_CWMMotion_somDefaultInit SOMObject_somDefaultInit
#define M_CWMMotion_somDestruct SOMObject_somDestruct
#define M_CWMMotion_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_CWMMotion_somDefaultAssign SOMObject_somDefaultAssign
#define M_CWMMotion_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_CWMMotion_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_CWMMotion_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_CWMMotion_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_CWMMotion_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_CWMMotion_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_CWMMotion_somInit SOMObject_somInit
#define M_CWMMotion_somFree SOMObject_somFree
#define M_CWMMotion_somUninit SOMObject_somUninit
#define M_CWMMotion_somGetClass SOMObject_somGetClass
#define M_CWMMotion_somGetClassName SOMObject_somGetClassName
#define M_CWMMotion_somGetSize SOMObject_somGetSize
#define M_CWMMotion_somIsA SOMObject_somIsA
#define M_CWMMotion_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_CWMMotion_somRespondsTo SOMObject_somRespondsTo
#define M_CWMMotion_somDispatch SOMObject_somDispatch
#define M_CWMMotion_somClassDispatch SOMObject_somClassDispatch
#define M_CWMMotion_somCastObj SOMObject_somCastObj
#define M_CWMMotion_somResetObj SOMObject_somResetObj
#define M_CWMMotion_somDispatchV SOMObject_somDispatchV
#define M_CWMMotion_somDispatchL SOMObject_somDispatchL
#define M_CWMMotion_somDispatchA SOMObject_somDispatchA
#define M_CWMMotion_somDispatchD SOMObject_somDispatchD
#define M_CWMMotion_somPrintSelf SOMObject_somPrintSelf
#define M_CWMMotion_somDumpSelf SOMObject_somDumpSelf
#define M_CWMMotion_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_CWMMotion_h */
