
/*
 * This file was generated by the SOM Compiler.
 * FileName: include\cwmov.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 * 
 * CWmov.idl:
 */


#ifndef SOM_CWMOV_h
#define SOM_CWMOV_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef CWMOV
#define CWMOV SOMObject
#endif
#include <cwvideo.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPDataFile
    #define M_WPDataFile SOMObject
#endif /* M_WPDataFile */
#ifndef M_CWMMDataFile
    #define M_CWMMDataFile SOMObject
#endif /* M_CWMMDataFile */
#ifndef M_CWVideo
    #define M_CWVideo SOMObject
#endif /* M_CWVideo */
#ifndef M_CWMOV
    #define M_CWMOV SOMObject
#endif /* M_CWMOV */

/*
 * End of user-defined types.
 */

/*
 * Passthru lines: File: "C.h", "after"
 */

#include "cwmmres.h"


#define CWMOV_MajorVersion 1
#define CWMOV_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define CWMOVNewClass cwmovc
#pragma linkage(cwmovc, system)
#define CWMOVClassData cwmovd
#define CWMOVCClassData cwmovx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <cwmov.h>
/*--------------Migration------------*/
#define CWMOV_classObj CWMOVClassData.classObject
#define _CWMOV CWMOV_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK CWMOVNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(CWMOVNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct CWMOVClassDataStructure {
	SOMClass *classObject;
} SOMDLINK CWMOVClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct CWMOVCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK CWMOVCClassData;

/*
 * New and Renew macros for CWMOV
 */
#define CWMOVNew() \
   (_somNew(_CWMOV ? _CWMOV : CWMOVNewClass(CWMOV_MajorVersion, CWMOV_MinorVersion)))
#define CWMOVRenew(buf) \
   (_somRenew(_CWMOV ? _CWMOV : CWMOVNewClass(CWMOV_MajorVersion, CWMOV_MinorVersion), buf))
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define CWMOV_wpAddFileTypePage WPDataFile_wpAddFileTypePage
#define CWMOV_wpPrintMetaFile WPDataFile_wpPrintMetaFile
#define CWMOV_wpPrintPifFile WPDataFile_wpPrintPifFile
#define CWMOV_wpPrintPrinterSpecificFile WPDataFile_wpPrintPrinterSpecificFile
#define CWMOV_wpPrintUnknownFile WPDataFile_wpPrintUnknownFile
#define CWMOV_wpQueryAssociatedProgram WPDataFile_wpQueryAssociatedProgram
#define CWMOV_wpSetAssociatedFileIcon WPDataFile_wpSetAssociatedFileIcon
#define CWMOV_wpQueryAssociatedFileIcon WPDataFile_wpQueryAssociatedFileIcon
#define CWMOV_wpSetRealName WPFileSystem_wpSetRealName
#define CWMOV_wpSetType WPFileSystem_wpSetType
#define CWMOV_wpQueryType WPFileSystem_wpQueryType
#define CWMOV_wpSetAttr WPFileSystem_wpSetAttr
#define CWMOV_wpQueryAttr WPFileSystem_wpQueryAttr
#define CWMOV_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define CWMOV_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define CWMOV_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define CWMOV_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define CWMOV_wpQueryCreation WPFileSystem_wpQueryCreation
#define CWMOV_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define CWMOV_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define CWMOV_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define CWMOV_wpQueryEASize WPFileSystem_wpQueryEASize
#define CWMOV_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define CWMOV_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define CWMOV_wpRefresh WPFileSystem_wpRefresh
#define CWMOV_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define CWMOV_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define CWMOV_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define CWMOV_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define CWMOV_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define CWMOV_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define CWMOV_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define CWMOV_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define CWMOV_wpQueryRealName WPFileSystem_wpQueryRealName
#define CWMOV_wpQueryFilename WPFileSystem_wpQueryFilename
#define CWMOV_wpQueryDisk WPFileSystem_wpQueryDisk
#define CWMOV_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define CWMOV_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define CWMOV_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define CWMOV_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define CWMOV_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define CWMOV_wpAddSettingsPages WPObject_wpAddSettingsPages
#define CWMOV_wpAddToObjUseList WPObject_wpAddToObjUseList
#define CWMOV_wpAllocMem WPObject_wpAllocMem
#define CWMOV_wpAppendObject WPObject_wpAppendObject
#define CWMOV_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define CWMOV_wpClose WPObject_wpClose
#define CWMOV_wpCnrInsertObject WPObject_wpCnrInsertObject
#define CWMOV_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define CWMOV_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define CWMOV_wpConfirmDelete WPObject_wpConfirmDelete
#define CWMOV_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define CWMOV_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define CWMOV_wpCopyObject WPObject_wpCopyObject
#define CWMOV_wpCreateAnother WPObject_wpCreateAnother
#define CWMOV_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define CWMOV_wpCreateShadowObject WPObject_wpCreateShadowObject
#define CWMOV_wpDelete WPObject_wpDelete
#define CWMOV_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define CWMOV_wpDisplayHelp WPObject_wpDisplayHelp
#define CWMOV_wpDisplayMenu WPObject_wpDisplayMenu
#define CWMOV_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define CWMOV_wpDraggedOverObject WPObject_wpDraggedOverObject
#define CWMOV_wpDragOver WPObject_wpDragOver
#define CWMOV_wpDrop WPObject_wpDrop
#define CWMOV_wpDroppedOnObject WPObject_wpDroppedOnObject
#define CWMOV_wpEndConversation WPObject_wpEndConversation
#define CWMOV_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define CWMOV_wpFindUseItem WPObject_wpFindUseItem
#define CWMOV_wpFormatDragItem WPObject_wpFormatDragItem
#define CWMOV_wpFree WPObject_wpFree
#define CWMOV_wpFreeMem WPObject_wpFreeMem
#define CWMOV_wpHide WPObject_wpHide
#define CWMOV_wpInitData WPObject_wpInitData
#define CWMOV_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define CWMOV_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define CWMOV_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define CWMOV_wpMenuItemSelected WPObject_wpMenuItemSelected
#define CWMOV_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define CWMOV_wpMoveObject WPObject_wpMoveObject
#define CWMOV_wpOpen WPObject_wpOpen
#define CWMOV_wpPrintObject WPObject_wpPrintObject
#define CWMOV_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define CWMOV_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define CWMOV_wpQueryConfirmations WPObject_wpQueryConfirmations
#define CWMOV_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define CWMOV_wpQueryDefaultView WPObject_wpQueryDefaultView
#define CWMOV_wpQueryDetailsData WPObject_wpQueryDetailsData
#define CWMOV_wpQueryError WPObject_wpQueryError
#define CWMOV_wpSetFolder WPObject_wpSetFolder
#define CWMOV_wpQueryFolder WPObject_wpQueryFolder
#define CWMOV_wpQueryIcon WPObject_wpQueryIcon
#define CWMOV_wpQueryIconData WPObject_wpQueryIconData
#define CWMOV_wpQueryMinWindow WPObject_wpQueryMinWindow
#define CWMOV_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define CWMOV_wpQueryStyle WPObject_wpQueryStyle
#define CWMOV_wpSetTaskRec WPObject_wpSetTaskRec
#define CWMOV_wpFindTaskRec WPObject_wpFindTaskRec
#define CWMOV_wpQueryTitle WPObject_wpQueryTitle
#define CWMOV_wpRegisterView WPObject_wpRegisterView
#define CWMOV_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define CWMOV_wpRender WPObject_wpRender
#define CWMOV_wpRenderComplete WPObject_wpRenderComplete
#define CWMOV_wpReplaceObject WPObject_wpReplaceObject
#define CWMOV_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define CWMOV_wpRestore WPObject_wpRestore
#define CWMOV_wpRestoreData WPObject_wpRestoreData
#define CWMOV_wpRestoreLong WPObject_wpRestoreLong
#define CWMOV_wpRestoreState WPObject_wpRestoreState
#define CWMOV_wpRestoreString WPObject_wpRestoreString
#define CWMOV_wpSaveData WPObject_wpSaveData
#define CWMOV_wpSaveImmediate WPObject_wpSaveImmediate
#define CWMOV_wpSaveDeferred WPObject_wpSaveDeferred
#define CWMOV_wpSaveLong WPObject_wpSaveLong
#define CWMOV_wpSaveState WPObject_wpSaveState
#define CWMOV_wpSaveString WPObject_wpSaveString
#define CWMOV_wpScanSetupString WPObject_wpScanSetupString
#define CWMOV_wpSetConcurrentView WPObject_wpSetConcurrentView
#define CWMOV_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define CWMOV_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define CWMOV_wpSetDefaultView WPObject_wpSetDefaultView
#define CWMOV_wpSetError WPObject_wpSetError
#define CWMOV_wpSetIconHandle WPObject_wpSetIconHandle
#define CWMOV_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define CWMOV_wpSetupOnce WPObject_wpSetupOnce
#define CWMOV_wpSetIcon WPObject_wpSetIcon
#define CWMOV_wpSetIconData WPObject_wpSetIconData
#define CWMOV_wpSetMinWindow WPObject_wpSetMinWindow
#define CWMOV_wpSetStyle WPObject_wpSetStyle
#define CWMOV_wpModifyStyle WPObject_wpModifyStyle
#define CWMOV_wpSetTitle WPObject_wpSetTitle
#define CWMOV_wpSetup WPObject_wpSetup
#define CWMOV_wpSwitchTo WPObject_wpSwitchTo
#define CWMOV_wpUnInitData WPObject_wpUnInitData
#define CWMOV_wpViewObject WPObject_wpViewObject
#define CWMOV_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define CWMOV_wpQueryHandle WPObject_wpQueryHandle
#define CWMOV_wpUnlockObject WPObject_wpUnlockObject
#define CWMOV_wpObjectReady WPObject_wpObjectReady
#define CWMOV_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define CWMOV_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define CWMOV_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define CWMOV_wpIsDeleteable WPObject_wpIsDeleteable
#define CWMOV_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define CWMOV_wpSetObjectID WPObject_wpSetObjectID
#define CWMOV_wpQueryObjectID WPObject_wpQueryObjectID
#define CWMOV_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define CWMOV_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define CWMOV_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define CWMOV_wpFindViewItem WPObject_wpFindViewItem
#define CWMOV_wpLockObject WPObject_wpLockObject
#define CWMOV_wpIsLocked WPObject_wpIsLocked
#define CWMOV_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define CWMOV_wpWaitForClose WPObject_wpWaitForClose
#define CWMOV_somDefaultInit SOMObject_somDefaultInit
#define CWMOV_somDestruct SOMObject_somDestruct
#define CWMOV_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define CWMOV_somDefaultAssign SOMObject_somDefaultAssign
#define CWMOV_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define CWMOV_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define CWMOV_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define CWMOV_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define CWMOV_somDefaultVAssign SOMObject_somDefaultVAssign
#define CWMOV_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define CWMOV_somInit SOMObject_somInit
#define CWMOV_somFree SOMObject_somFree
#define CWMOV_somUninit SOMObject_somUninit
#define CWMOV_somGetClass SOMObject_somGetClass
#define CWMOV_somGetClassName SOMObject_somGetClassName
#define CWMOV_somGetSize SOMObject_somGetSize
#define CWMOV_somIsA SOMObject_somIsA
#define CWMOV_somIsInstanceOf SOMObject_somIsInstanceOf
#define CWMOV_somRespondsTo SOMObject_somRespondsTo
#define CWMOV_somDispatch SOMObject_somDispatch
#define CWMOV_somClassDispatch SOMObject_somClassDispatch
#define CWMOV_somCastObj SOMObject_somCastObj
#define CWMOV_somResetObj SOMObject_somResetObj
#define CWMOV_somDispatchV SOMObject_somDispatchV
#define CWMOV_somDispatchL SOMObject_somDispatchL
#define CWMOV_somDispatchA SOMObject_somDispatchA
#define CWMOV_somDispatchD SOMObject_somDispatchD
#define CWMOV_somPrintSelf SOMObject_somPrintSelf
#define CWMOV_somDumpSelf SOMObject_somDumpSelf
#define CWMOV_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_CWMOV_h */

#ifndef SOM_M_CWMOV_h
#define SOM_M_CWMOV_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_CWMOV
#define M_CWMOV SOMObject
#endif
#include <cwvideo.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_CWMOV_MajorVersion 1
#define M_CWMOV_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_CWMOVNewClass cwmovMc
#pragma linkage(cwmovMc, system)
#define M_CWMOVClassData cwmovMd
#define M_CWMOVCClassData cwmovMx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_CWMOV_classObj M_CWMOVClassData.classObject
#define _M_CWMOV M_CWMOV_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_CWMOVNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_CWMOVNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_CWMOVClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_CWMOVClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_CWMOVCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_CWMOVCClassData;

/*
 * New and Renew macros for M_CWMOV
 */
#define M_CWMOVNew() \
   (_somNew(_M_CWMOV ? _M_CWMOV : M_CWMOVNewClass(M_CWMOV_MajorVersion, M_CWMOV_MinorVersion)))
#define M_CWMOVRenew(buf) \
   (_somRenew(_M_CWMOV ? _M_CWMOV : M_CWMOVNewClass(M_CWMOV_MajorVersion, M_CWMOV_MinorVersion), buf))

/*
 * Override method: wpclsQueryTitle
 */
#define M_CWMOV_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryInstanceType
 */
#define M_CWMOV_wpclsQueryInstanceType(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceType(somSelf)

/*
 * Override method: wpclsQueryInstanceFilter
 */
#define M_CWMOV_wpclsQueryInstanceFilter(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceFilter(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_CWMOV_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryDefaultHelp
 */
#define M_CWMOV_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary) \
	M_WPObject_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_CWMOV_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_CWMOV_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_CWMOV_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_CWMOV_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_CWMOV_wpclsInitData M_WPObject_wpclsInitData
#define M_CWMOV_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_CWMOV_wpclsNew M_WPObject_wpclsNew
#define M_CWMOV_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_CWMOV_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_CWMOV_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_CWMOV_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_CWMOV_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_CWMOV_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_CWMOV_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_CWMOV_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_CWMOV_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_CWMOV_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_CWMOV_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_CWMOV_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_CWMOV_wpclsSetError M_WPObject_wpclsSetError
#define M_CWMOV_wpclsQueryError M_WPObject_wpclsQueryError
#define M_CWMOV_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_CWMOV_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_CWMOV_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_CWMOV_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_CWMOV_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_CWMOV_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_CWMOV_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_CWMOV_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_CWMOV_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_CWMOV_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_CWMOV_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_CWMOV_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_CWMOV__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_CWMOV__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_CWMOV__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_CWMOV__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_CWMOV_somNew SOMClass_somNew
#define M_CWMOV_somNewNoInit SOMClass_somNewNoInit
#define M_CWMOV_somRenew SOMClass_somRenew
#define M_CWMOV_somRenewNoInit SOMClass_somRenewNoInit
#define M_CWMOV_somRenewNoZero SOMClass_somRenewNoZero
#define M_CWMOV_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_CWMOV_somAllocate SOMClass_somAllocate
#define M_CWMOV_somDeallocate SOMClass_somDeallocate
#define M_CWMOV__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_CWMOV__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_CWMOV_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_CWMOV_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_CWMOV_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_CWMOV_somInitClass SOMClass_somInitClass
#define M_CWMOV_somInitMIClass SOMClass_somInitMIClass
#define M_CWMOV_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_CWMOV_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_CWMOV_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_CWMOV_somClassReady SOMClass_somClassReady
#define M_CWMOV_somGetApplyStub SOMClass_somGetApplyStub
#define M_CWMOV_somGetClassData SOMClass_somGetClassData
#define M_CWMOV_somSetClassData SOMClass_somSetClassData
#define M_CWMOV_somGetClassMtab SOMClass_somGetClassMtab
#define M_CWMOV_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_CWMOV_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_CWMOV_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_CWMOV_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_CWMOV_somGetMemberToken SOMClass_somGetMemberToken
#define M_CWMOV_somGetMethodData SOMClass_somGetMethodData
#define M_CWMOV_somGetRdStub SOMClass_somGetRdStub
#define M_CWMOV_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_CWMOV_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_CWMOV_somGetMethodToken SOMClass_somGetMethodToken
#define M_CWMOV_somGetName SOMClass_somGetName
#define M_CWMOV_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_CWMOV_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_CWMOV_somGetNumMethods SOMClass_somGetNumMethods
#define M_CWMOV_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_CWMOV_somGetParent SOMClass_somGetParent
#define M_CWMOV_somGetParents SOMClass_somGetParents
#define M_CWMOV_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_CWMOV_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_CWMOV_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_CWMOV_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_CWMOV_somFindMethod SOMClass_somFindMethod
#define M_CWMOV_somFindMethodOk SOMClass_somFindMethodOk
#define M_CWMOV_somFindSMethod SOMClass_somFindSMethod
#define M_CWMOV_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_CWMOV_somLookupMethod SOMClass_somLookupMethod
#define M_CWMOV_somCheckVersion SOMClass_somCheckVersion
#define M_CWMOV_somDescendedFrom SOMClass_somDescendedFrom
#define M_CWMOV_somSupportsMethod SOMClass_somSupportsMethod
#define M_CWMOV_somDefinedMethod SOMClass_somDefinedMethod
#define M_CWMOV_somOverrideMtab SOMClass_somOverrideMtab
#define M_CWMOV_somDefaultInit SOMObject_somDefaultInit
#define M_CWMOV_somDestruct SOMObject_somDestruct
#define M_CWMOV_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_CWMOV_somDefaultAssign SOMObject_somDefaultAssign
#define M_CWMOV_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_CWMOV_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_CWMOV_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_CWMOV_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_CWMOV_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_CWMOV_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_CWMOV_somInit SOMObject_somInit
#define M_CWMOV_somFree SOMObject_somFree
#define M_CWMOV_somUninit SOMObject_somUninit
#define M_CWMOV_somGetClass SOMObject_somGetClass
#define M_CWMOV_somGetClassName SOMObject_somGetClassName
#define M_CWMOV_somGetSize SOMObject_somGetSize
#define M_CWMOV_somIsA SOMObject_somIsA
#define M_CWMOV_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_CWMOV_somRespondsTo SOMObject_somRespondsTo
#define M_CWMOV_somDispatch SOMObject_somDispatch
#define M_CWMOV_somClassDispatch SOMObject_somClassDispatch
#define M_CWMOV_somCastObj SOMObject_somCastObj
#define M_CWMOV_somResetObj SOMObject_somResetObj
#define M_CWMOV_somDispatchV SOMObject_somDispatchV
#define M_CWMOV_somDispatchL SOMObject_somDispatchL
#define M_CWMOV_somDispatchA SOMObject_somDispatchA
#define M_CWMOV_somDispatchD SOMObject_somDispatchD
#define M_CWMOV_somPrintSelf SOMObject_somPrintSelf
#define M_CWMOV_somDumpSelf SOMObject_somDumpSelf
#define M_CWMOV_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_CWMOV_h */
