
/*
 * This file was generated by the SOM Compiler.
 * FileName: include\mmaudio.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 * 
 * MMAudio.idl:
 */


#ifndef SOM_MMAudio_h
#define SOM_MMAudio_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef MMAudio
#define MMAudio SOMObject
#endif
#include <mmdataf.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPDataFile
    #define M_WPDataFile SOMObject
#endif /* M_WPDataFile */
#ifndef M_MMDataFile
    #define M_MMDataFile SOMObject
#endif /* M_MMDataFile */
#ifndef M_MMAudio
    #define M_MMAudio SOMObject
#endif /* M_MMAudio */

/*
 * End of user-defined types.
 */

#define MMAudio_MajorVersion 1
#define MMAudio_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define MMAudioNewClass mmaudioc
#pragma linkage(mmaudioc, system)
#define MMAudioClassData mmaudiod
#define MMAudioCClassData mmaudiox
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <mmaudio.h>
/*--------------Migration------------*/
#define MMAudio_classObj MMAudioClassData.classObject
#define _MMAudio MMAudio_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK MMAudioNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(MMAudioNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct MMAudioClassDataStructure {
	SOMClass *classObject;
} SOMDLINK MMAudioClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct MMAudioCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK MMAudioCClassData;

/*
 * New and Renew macros for MMAudio
 */
#define MMAudioNew() \
   (_somNew(_MMAudio ? _MMAudio : MMAudioNewClass(MMAudio_MajorVersion, MMAudio_MinorVersion)))
#define MMAudioRenew(buf) \
   (_somRenew(_MMAudio ? _MMAudio : MMAudioNewClass(MMAudio_MajorVersion, MMAudio_MinorVersion), buf))

/*
 * Override method: mmFilterPopupMenu
 */
#define MMAudio_mmFilterPopupMenu(somSelf,ulFlags,hwndcnr,fMultiSelect) \
	MMDataFile_mmFilterPopupMenu(somSelf,ulFlags,hwndcnr,fMultiSelect)

/*
 * Override method: mmViewNotify
 */
#define MMAudio_mmViewNotify(somSelf) \
	MMDataFile_mmViewNotify(somSelf)

/*
 * Override method: wpFormatDragItem
 */
#define MMAudio_wpFormatDragItem(somSelf,pdrgItem) \
	WPObject_wpFormatDragItem(somSelf,pdrgItem)

/*
 * Override method: wpMenuItemSelected
 */
#define MMAudio_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpModifyPopupMenu
 */
#define MMAudio_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpOpen
 */
#define MMAudio_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpQueryDefaultView
 */
#define MMAudio_wpQueryDefaultView(somSelf) \
	WPObject_wpQueryDefaultView(somSelf)

/*
 * Override method: wpUnInitData
 */
#define MMAudio_wpUnInitData(somSelf) \
	WPObject_wpUnInitData(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define MMAudio_mmDetermineViewFor MMDataFile_mmDetermineViewFor
#define MMAudio_wpAddFileTypePage WPDataFile_wpAddFileTypePage
#define MMAudio_wpPrintMetaFile WPDataFile_wpPrintMetaFile
#define MMAudio_wpPrintPifFile WPDataFile_wpPrintPifFile
#define MMAudio_wpPrintPrinterSpecificFile WPDataFile_wpPrintPrinterSpecificFile
#define MMAudio_wpPrintUnknownFile WPDataFile_wpPrintUnknownFile
#define MMAudio_wpQueryAssociatedProgram WPDataFile_wpQueryAssociatedProgram
#define MMAudio_wpSetAssociatedFileIcon WPDataFile_wpSetAssociatedFileIcon
#define MMAudio_wpQueryAssociatedFileIcon WPDataFile_wpQueryAssociatedFileIcon
#define MMAudio_wpSetRealName WPFileSystem_wpSetRealName
#define MMAudio_wpSetType WPFileSystem_wpSetType
#define MMAudio_wpQueryType WPFileSystem_wpQueryType
#define MMAudio_wpSetAttr WPFileSystem_wpSetAttr
#define MMAudio_wpQueryAttr WPFileSystem_wpQueryAttr
#define MMAudio_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define MMAudio_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define MMAudio_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define MMAudio_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define MMAudio_wpQueryCreation WPFileSystem_wpQueryCreation
#define MMAudio_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define MMAudio_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define MMAudio_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define MMAudio_wpQueryEASize WPFileSystem_wpQueryEASize
#define MMAudio_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define MMAudio_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define MMAudio_wpRefresh WPFileSystem_wpRefresh
#define MMAudio_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define MMAudio_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define MMAudio_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define MMAudio_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define MMAudio_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define MMAudio_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define MMAudio_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define MMAudio_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define MMAudio_wpQueryRealName WPFileSystem_wpQueryRealName
#define MMAudio_wpQueryFilename WPFileSystem_wpQueryFilename
#define MMAudio_wpQueryDisk WPFileSystem_wpQueryDisk
#define MMAudio_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define MMAudio_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define MMAudio_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define MMAudio_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define MMAudio_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define MMAudio_wpAddSettingsPages WPObject_wpAddSettingsPages
#define MMAudio_wpAddToObjUseList WPObject_wpAddToObjUseList
#define MMAudio_wpAllocMem WPObject_wpAllocMem
#define MMAudio_wpAppendObject WPObject_wpAppendObject
#define MMAudio_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define MMAudio_wpClose WPObject_wpClose
#define MMAudio_wpCnrInsertObject WPObject_wpCnrInsertObject
#define MMAudio_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define MMAudio_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define MMAudio_wpConfirmDelete WPObject_wpConfirmDelete
#define MMAudio_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define MMAudio_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define MMAudio_wpCopyObject WPObject_wpCopyObject
#define MMAudio_wpCreateAnother WPObject_wpCreateAnother
#define MMAudio_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define MMAudio_wpCreateShadowObject WPObject_wpCreateShadowObject
#define MMAudio_wpDelete WPObject_wpDelete
#define MMAudio_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define MMAudio_wpDisplayHelp WPObject_wpDisplayHelp
#define MMAudio_wpDisplayMenu WPObject_wpDisplayMenu
#define MMAudio_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define MMAudio_wpDraggedOverObject WPObject_wpDraggedOverObject
#define MMAudio_wpDragOver WPObject_wpDragOver
#define MMAudio_wpDrop WPObject_wpDrop
#define MMAudio_wpDroppedOnObject WPObject_wpDroppedOnObject
#define MMAudio_wpEndConversation WPObject_wpEndConversation
#define MMAudio_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define MMAudio_wpFindUseItem WPObject_wpFindUseItem
#define MMAudio_wpFree WPObject_wpFree
#define MMAudio_wpFreeMem WPObject_wpFreeMem
#define MMAudio_wpHide WPObject_wpHide
#define MMAudio_wpInitData WPObject_wpInitData
#define MMAudio_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define MMAudio_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define MMAudio_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define MMAudio_wpMoveObject WPObject_wpMoveObject
#define MMAudio_wpPrintObject WPObject_wpPrintObject
#define MMAudio_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define MMAudio_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define MMAudio_wpQueryConfirmations WPObject_wpQueryConfirmations
#define MMAudio_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define MMAudio_wpQueryDetailsData WPObject_wpQueryDetailsData
#define MMAudio_wpQueryError WPObject_wpQueryError
#define MMAudio_wpSetFolder WPObject_wpSetFolder
#define MMAudio_wpQueryFolder WPObject_wpQueryFolder
#define MMAudio_wpQueryIcon WPObject_wpQueryIcon
#define MMAudio_wpQueryIconData WPObject_wpQueryIconData
#define MMAudio_wpQueryMinWindow WPObject_wpQueryMinWindow
#define MMAudio_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define MMAudio_wpQueryStyle WPObject_wpQueryStyle
#define MMAudio_wpSetTaskRec WPObject_wpSetTaskRec
#define MMAudio_wpFindTaskRec WPObject_wpFindTaskRec
#define MMAudio_wpQueryTitle WPObject_wpQueryTitle
#define MMAudio_wpRegisterView WPObject_wpRegisterView
#define MMAudio_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define MMAudio_wpRender WPObject_wpRender
#define MMAudio_wpRenderComplete WPObject_wpRenderComplete
#define MMAudio_wpReplaceObject WPObject_wpReplaceObject
#define MMAudio_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define MMAudio_wpRestore WPObject_wpRestore
#define MMAudio_wpRestoreData WPObject_wpRestoreData
#define MMAudio_wpRestoreLong WPObject_wpRestoreLong
#define MMAudio_wpRestoreState WPObject_wpRestoreState
#define MMAudio_wpRestoreString WPObject_wpRestoreString
#define MMAudio_wpSaveData WPObject_wpSaveData
#define MMAudio_wpSaveImmediate WPObject_wpSaveImmediate
#define MMAudio_wpSaveDeferred WPObject_wpSaveDeferred
#define MMAudio_wpSaveLong WPObject_wpSaveLong
#define MMAudio_wpSaveState WPObject_wpSaveState
#define MMAudio_wpSaveString WPObject_wpSaveString
#define MMAudio_wpScanSetupString WPObject_wpScanSetupString
#define MMAudio_wpSetConcurrentView WPObject_wpSetConcurrentView
#define MMAudio_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define MMAudio_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define MMAudio_wpSetDefaultView WPObject_wpSetDefaultView
#define MMAudio_wpSetError WPObject_wpSetError
#define MMAudio_wpSetIconHandle WPObject_wpSetIconHandle
#define MMAudio_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define MMAudio_wpSetupOnce WPObject_wpSetupOnce
#define MMAudio_wpSetIcon WPObject_wpSetIcon
#define MMAudio_wpSetIconData WPObject_wpSetIconData
#define MMAudio_wpSetMinWindow WPObject_wpSetMinWindow
#define MMAudio_wpSetStyle WPObject_wpSetStyle
#define MMAudio_wpModifyStyle WPObject_wpModifyStyle
#define MMAudio_wpSetTitle WPObject_wpSetTitle
#define MMAudio_wpSetup WPObject_wpSetup
#define MMAudio_wpSwitchTo WPObject_wpSwitchTo
#define MMAudio_wpViewObject WPObject_wpViewObject
#define MMAudio_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define MMAudio_wpQueryHandle WPObject_wpQueryHandle
#define MMAudio_wpUnlockObject WPObject_wpUnlockObject
#define MMAudio_wpObjectReady WPObject_wpObjectReady
#define MMAudio_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define MMAudio_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define MMAudio_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define MMAudio_wpIsDeleteable WPObject_wpIsDeleteable
#define MMAudio_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define MMAudio_wpSetObjectID WPObject_wpSetObjectID
#define MMAudio_wpQueryObjectID WPObject_wpQueryObjectID
#define MMAudio_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define MMAudio_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define MMAudio_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define MMAudio_wpFindViewItem WPObject_wpFindViewItem
#define MMAudio_wpLockObject WPObject_wpLockObject
#define MMAudio_wpIsLocked WPObject_wpIsLocked
#define MMAudio_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define MMAudio_wpWaitForClose WPObject_wpWaitForClose
#define MMAudio_somDefaultInit SOMObject_somDefaultInit
#define MMAudio_somDestruct SOMObject_somDestruct
#define MMAudio_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define MMAudio_somDefaultAssign SOMObject_somDefaultAssign
#define MMAudio_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define MMAudio_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define MMAudio_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define MMAudio_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define MMAudio_somDefaultVAssign SOMObject_somDefaultVAssign
#define MMAudio_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define MMAudio_somInit SOMObject_somInit
#define MMAudio_somFree SOMObject_somFree
#define MMAudio_somUninit SOMObject_somUninit
#define MMAudio_somGetClass SOMObject_somGetClass
#define MMAudio_somGetClassName SOMObject_somGetClassName
#define MMAudio_somGetSize SOMObject_somGetSize
#define MMAudio_somIsA SOMObject_somIsA
#define MMAudio_somIsInstanceOf SOMObject_somIsInstanceOf
#define MMAudio_somRespondsTo SOMObject_somRespondsTo
#define MMAudio_somDispatch SOMObject_somDispatch
#define MMAudio_somClassDispatch SOMObject_somClassDispatch
#define MMAudio_somCastObj SOMObject_somCastObj
#define MMAudio_somResetObj SOMObject_somResetObj
#define MMAudio_somDispatchV SOMObject_somDispatchV
#define MMAudio_somDispatchL SOMObject_somDispatchL
#define MMAudio_somDispatchA SOMObject_somDispatchA
#define MMAudio_somDispatchD SOMObject_somDispatchD
#define MMAudio_somPrintSelf SOMObject_somPrintSelf
#define MMAudio_somDumpSelf SOMObject_somDumpSelf
#define MMAudio_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_MMAudio_h */

#ifndef SOM_M_MMAudio_h
#define SOM_M_MMAudio_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_MMAudio
#define M_MMAudio SOMObject
#endif
#include <mmdataf.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_MMAudio_MajorVersion 1
#define M_MMAudio_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_MMAudioNewClass mmaudioMc
#pragma linkage(mmaudioMc, system)
#define M_MMAudioClassData mmaudioMd
#define M_MMAudioCClassData mmaudioMx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_MMAudio_classObj M_MMAudioClassData.classObject
#define _M_MMAudio M_MMAudio_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_MMAudioNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_MMAudioNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_MMAudioClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_MMAudioClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_MMAudioCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_MMAudioCClassData;

/*
 * New and Renew macros for M_MMAudio
 */
#define M_MMAudioNew() \
   (_somNew(_M_MMAudio ? _M_MMAudio : M_MMAudioNewClass(M_MMAudio_MajorVersion, M_MMAudio_MinorVersion)))
#define M_MMAudioRenew(buf) \
   (_somRenew(_M_MMAudio ? _M_MMAudio : M_MMAudioNewClass(M_MMAudio_MajorVersion, M_MMAudio_MinorVersion), buf))

/*
 * Override method: mmclsDeleteFromTypeList
 */
#define M_MMAudio_mmclsDeleteFromTypeList(somSelf,pszType) \
	M_MMDataFile_mmclsDeleteFromTypeList(somSelf,pszType)

/*
 * Override method: mmclsDeleteFromExtensionList
 */
#define M_MMAudio_mmclsDeleteFromExtensionList(somSelf,pszExt) \
	M_MMDataFile_mmclsDeleteFromExtensionList(somSelf,pszExt)

/*
 * Override method: mmclsInitTypesAndExtensions
 */
#define M_MMAudio_mmclsInitTypesAndExtensions(somSelf) \
	M_MMDataFile_mmclsInitTypesAndExtensions(somSelf)

/*
 * Override method: wpclsQueryInstanceType
 */
#define M_MMAudio_wpclsQueryInstanceType(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceType(somSelf)

/*
 * Override method: wpclsQueryInstanceFilter
 */
#define M_MMAudio_wpclsQueryInstanceFilter(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceFilter(somSelf)

/*
 * Override method: wpclsInitData
 */
#define M_MMAudio_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsQueryDefaultHelp
 */
#define M_MMAudio_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary) \
	M_WPObject_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary)

/*
 * Override method: wpclsQueryTitle
 */
#define M_MMAudio_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_MMAudio_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_MMAudio_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_MMAudio_mmclsSetDefaultView M_MMDataFile_mmclsSetDefaultView
#define M_MMAudio_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_MMAudio_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_MMAudio_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_MMAudio_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_MMAudio_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_MMAudio_wpclsNew M_WPObject_wpclsNew
#define M_MMAudio_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_MMAudio_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_MMAudio_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_MMAudio_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_MMAudio_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_MMAudio_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_MMAudio_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_MMAudio_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_MMAudio_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_MMAudio_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_MMAudio_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_MMAudio_wpclsSetError M_WPObject_wpclsSetError
#define M_MMAudio_wpclsQueryError M_WPObject_wpclsQueryError
#define M_MMAudio_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_MMAudio_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_MMAudio_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_MMAudio_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_MMAudio_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_MMAudio_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_MMAudio_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_MMAudio_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_MMAudio_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_MMAudio_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_MMAudio_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_MMAudio_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_MMAudio__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_MMAudio__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_MMAudio__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_MMAudio__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_MMAudio_somNew SOMClass_somNew
#define M_MMAudio_somNewNoInit SOMClass_somNewNoInit
#define M_MMAudio_somRenew SOMClass_somRenew
#define M_MMAudio_somRenewNoInit SOMClass_somRenewNoInit
#define M_MMAudio_somRenewNoZero SOMClass_somRenewNoZero
#define M_MMAudio_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_MMAudio_somAllocate SOMClass_somAllocate
#define M_MMAudio_somDeallocate SOMClass_somDeallocate
#define M_MMAudio__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_MMAudio__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_MMAudio_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_MMAudio_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_MMAudio_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_MMAudio_somInitClass SOMClass_somInitClass
#define M_MMAudio_somInitMIClass SOMClass_somInitMIClass
#define M_MMAudio_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_MMAudio_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_MMAudio_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_MMAudio_somClassReady SOMClass_somClassReady
#define M_MMAudio_somGetApplyStub SOMClass_somGetApplyStub
#define M_MMAudio_somGetClassData SOMClass_somGetClassData
#define M_MMAudio_somSetClassData SOMClass_somSetClassData
#define M_MMAudio_somGetClassMtab SOMClass_somGetClassMtab
#define M_MMAudio_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_MMAudio_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_MMAudio_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_MMAudio_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_MMAudio_somGetMemberToken SOMClass_somGetMemberToken
#define M_MMAudio_somGetMethodData SOMClass_somGetMethodData
#define M_MMAudio_somGetRdStub SOMClass_somGetRdStub
#define M_MMAudio_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_MMAudio_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_MMAudio_somGetMethodToken SOMClass_somGetMethodToken
#define M_MMAudio_somGetName SOMClass_somGetName
#define M_MMAudio_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_MMAudio_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_MMAudio_somGetNumMethods SOMClass_somGetNumMethods
#define M_MMAudio_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_MMAudio_somGetParent SOMClass_somGetParent
#define M_MMAudio_somGetParents SOMClass_somGetParents
#define M_MMAudio_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_MMAudio_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_MMAudio_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_MMAudio_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_MMAudio_somFindMethod SOMClass_somFindMethod
#define M_MMAudio_somFindMethodOk SOMClass_somFindMethodOk
#define M_MMAudio_somFindSMethod SOMClass_somFindSMethod
#define M_MMAudio_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_MMAudio_somLookupMethod SOMClass_somLookupMethod
#define M_MMAudio_somCheckVersion SOMClass_somCheckVersion
#define M_MMAudio_somDescendedFrom SOMClass_somDescendedFrom
#define M_MMAudio_somSupportsMethod SOMClass_somSupportsMethod
#define M_MMAudio_somDefinedMethod SOMClass_somDefinedMethod
#define M_MMAudio_somOverrideMtab SOMClass_somOverrideMtab
#define M_MMAudio_somDefaultInit SOMObject_somDefaultInit
#define M_MMAudio_somDestruct SOMObject_somDestruct
#define M_MMAudio_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_MMAudio_somDefaultAssign SOMObject_somDefaultAssign
#define M_MMAudio_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_MMAudio_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_MMAudio_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_MMAudio_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_MMAudio_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_MMAudio_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_MMAudio_somInit SOMObject_somInit
#define M_MMAudio_somFree SOMObject_somFree
#define M_MMAudio_somUninit SOMObject_somUninit
#define M_MMAudio_somGetClass SOMObject_somGetClass
#define M_MMAudio_somGetClassName SOMObject_somGetClassName
#define M_MMAudio_somGetSize SOMObject_somGetSize
#define M_MMAudio_somIsA SOMObject_somIsA
#define M_MMAudio_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_MMAudio_somRespondsTo SOMObject_somRespondsTo
#define M_MMAudio_somDispatch SOMObject_somDispatch
#define M_MMAudio_somClassDispatch SOMObject_somClassDispatch
#define M_MMAudio_somCastObj SOMObject_somCastObj
#define M_MMAudio_somResetObj SOMObject_somResetObj
#define M_MMAudio_somDispatchV SOMObject_somDispatchV
#define M_MMAudio_somDispatchL SOMObject_somDispatchL
#define M_MMAudio_somDispatchA SOMObject_somDispatchA
#define M_MMAudio_somDispatchD SOMObject_somDispatchD
#define M_MMAudio_somPrintSelf SOMObject_somPrintSelf
#define M_MMAudio_somDumpSelf SOMObject_somDumpSelf
#define M_MMAudio_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_MMAudio_h */
