
/*
 * This file was generated by the SOM Compiler.
 * FileName: include\mmfolder.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 * 
 * mmfolder.idl:
 * 
 * 
 */


#ifndef SOM_MMFolder_h
#define SOM_MMFolder_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef MMFolder
#define MMFolder SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPFolder
    #define M_WPFolder SOMObject
#endif /* M_WPFolder */
#ifndef M_MMFolder
    #define M_MMFolder SOMObject
#endif /* M_MMFolder */

/*
 * End of user-defined types.
 */

#define MMFolder_MajorVersion 1
#define MMFolder_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define MMFolderNewClass mmfolderc
#pragma linkage(mmfolderc, system)
#define MMFolderClassData mmfolderd
#define MMFolderCClassData mmfolderx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <mmfolder.h>
/*--------------Migration------------*/
#define MMFolder_classObj MMFolderClassData.classObject
#define _MMFolder MMFolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK MMFolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(MMFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct MMFolderClassDataStructure {
	SOMClass *classObject;
} SOMDLINK MMFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct MMFolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK MMFolderCClassData;

/*
 * New and Renew macros for MMFolder
 */
#define MMFolderNew() \
   (_somNew(_MMFolder ? _MMFolder : MMFolderNewClass(MMFolder_MajorVersion, MMFolder_MinorVersion)))
#define MMFolderRenew(buf) \
   (_somRenew(_MMFolder ? _MMFolder : MMFolderNewClass(MMFolder_MajorVersion, MMFolder_MinorVersion), buf))

/*
 * Override method: wpOpen
 */
#define MMFolder_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpRestoreState
 */
#define MMFolder_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpSaveState
 */
#define MMFolder_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpMenuItemSelected
 */
#define MMFolder_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpObjectReady
 */
#define MMFolder_wpObjectReady(somSelf,ulCode,refObject) \
	WPObject_wpObjectReady(somSelf,ulCode,refObject)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define MMFolder_wpSetFldrFlags WPFolder_wpSetFldrFlags
#define MMFolder_wpQueryFldrFlags WPFolder_wpQueryFldrFlags
#define MMFolder_wpSetFldrFont WPFolder_wpSetFldrFont
#define MMFolder_wpQueryFldrFont WPFolder_wpQueryFldrFont
#define MMFolder_wpSetFldrAttr WPFolder_wpSetFldrAttr
#define MMFolder_wpQueryFldrAttr WPFolder_wpQueryFldrAttr
#define MMFolder_wpSetNextIconPos WPFolder_wpSetNextIconPos
#define MMFolder_wpQueryNextIconPos WPFolder_wpQueryNextIconPos
#define MMFolder_wpPopulate WPFolder_wpPopulate
#define MMFolder_wpQueryContent WPFolder_wpQueryContent
#define MMFolder_wpAddFolderView1Page WPFolder_wpAddFolderView1Page
#define MMFolder_wpAddFolderView2Page WPFolder_wpAddFolderView2Page
#define MMFolder_wpAddFolderView3Page WPFolder_wpAddFolderView3Page
#define MMFolder_wpAddFolderIncludePage WPFolder_wpAddFolderIncludePage
#define MMFolder_wpAddFolderSortPage WPFolder_wpAddFolderSortPage
#define MMFolder_wpAddFolderBackgroundPage WPFolder_wpAddFolderBackgroundPage
#define MMFolder_wpAddFolderSelfClosePage WPFolder_wpAddFolderSelfClosePage
#define MMFolder_wpInitIconPosData WPFolder_wpInitIconPosData
#define MMFolder_wpFreeIconPosData WPFolder_wpFreeIconPosData
#define MMFolder_wpStoreIconPosData WPFolder_wpStoreIconPosData
#define MMFolder_wpQueryIconPosition WPFolder_wpQueryIconPosition
#define MMFolder_wpSetFldrSort WPFolder_wpSetFldrSort
#define MMFolder_wpQueryFldrSort WPFolder_wpQueryFldrSort
#define MMFolder_wpRestoreFldrRunObjs WPFolder_wpRestoreFldrRunObjs
#define MMFolder_wpStoreFldrRunObjs WPFolder_wpStoreFldrRunObjs
#define MMFolder_wpHideFldrRunObjs WPFolder_wpHideFldrRunObjs
#define MMFolder_wpDeleteContents WPFolder_wpDeleteContents
#define MMFolder_wpSetFldrDetailsClass WPFolder_wpSetFldrDetailsClass
#define MMFolder_wpQueryFldrDetailsClass WPFolder_wpQueryFldrDetailsClass
#define MMFolder_wpSearchFolder WPFolder_wpSearchFolder
#define MMFolder_wpContainsFolders WPFolder_wpContainsFolders
#define MMFolder_wpQueryOpenFolders WPFolder_wpQueryOpenFolders
#define MMFolder_wpModifyFldrFlags WPFolder_wpModifyFldrFlags
#define MMFolder_wpAddToContent WPFolder_wpAddToContent
#define MMFolder_wpDeleteFromContent WPFolder_wpDeleteFromContent
#define MMFolder_wpSetDetailsColumnVisibility WPFolder_wpSetDetailsColumnVisibility
#define MMFolder_wpIsDetailsColumnVisible WPFolder_wpIsDetailsColumnVisible
#define MMFolder_wpSetFldrSortClass WPFolder_wpSetFldrSortClass
#define MMFolder_wpQueryFldrSortClass WPFolder_wpQueryFldrSortClass
#define MMFolder_wpSetSortAttribAvailable WPFolder_wpSetSortAttribAvailable
#define MMFolder_wpIsSortAttribAvailable WPFolder_wpIsSortAttribAvailable
#define MMFolder_wpQueryIconViewPos WPFolder_wpQueryIconViewPos
#define MMFolder_wpAddFirstChild WPFolder_wpAddFirstChild
#define MMFolder_wpSetRealName WPFileSystem_wpSetRealName
#define MMFolder_wpSetType WPFileSystem_wpSetType
#define MMFolder_wpQueryType WPFileSystem_wpQueryType
#define MMFolder_wpSetAttr WPFileSystem_wpSetAttr
#define MMFolder_wpQueryAttr WPFileSystem_wpQueryAttr
#define MMFolder_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define MMFolder_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define MMFolder_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define MMFolder_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define MMFolder_wpQueryCreation WPFileSystem_wpQueryCreation
#define MMFolder_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define MMFolder_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define MMFolder_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define MMFolder_wpQueryEASize WPFileSystem_wpQueryEASize
#define MMFolder_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define MMFolder_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define MMFolder_wpRefresh WPFileSystem_wpRefresh
#define MMFolder_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define MMFolder_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define MMFolder_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define MMFolder_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define MMFolder_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define MMFolder_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define MMFolder_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define MMFolder_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define MMFolder_wpQueryRealName WPFileSystem_wpQueryRealName
#define MMFolder_wpQueryFilename WPFileSystem_wpQueryFilename
#define MMFolder_wpQueryDisk WPFileSystem_wpQueryDisk
#define MMFolder_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define MMFolder_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define MMFolder_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define MMFolder_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define MMFolder_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define MMFolder_wpAddSettingsPages WPObject_wpAddSettingsPages
#define MMFolder_wpAddToObjUseList WPObject_wpAddToObjUseList
#define MMFolder_wpAllocMem WPObject_wpAllocMem
#define MMFolder_wpAppendObject WPObject_wpAppendObject
#define MMFolder_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define MMFolder_wpClose WPObject_wpClose
#define MMFolder_wpCnrInsertObject WPObject_wpCnrInsertObject
#define MMFolder_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define MMFolder_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define MMFolder_wpConfirmDelete WPObject_wpConfirmDelete
#define MMFolder_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define MMFolder_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define MMFolder_wpCopyObject WPObject_wpCopyObject
#define MMFolder_wpCreateAnother WPObject_wpCreateAnother
#define MMFolder_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define MMFolder_wpCreateShadowObject WPObject_wpCreateShadowObject
#define MMFolder_wpDelete WPObject_wpDelete
#define MMFolder_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define MMFolder_wpDisplayHelp WPObject_wpDisplayHelp
#define MMFolder_wpDisplayMenu WPObject_wpDisplayMenu
#define MMFolder_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define MMFolder_wpDraggedOverObject WPObject_wpDraggedOverObject
#define MMFolder_wpDragOver WPObject_wpDragOver
#define MMFolder_wpDrop WPObject_wpDrop
#define MMFolder_wpDroppedOnObject WPObject_wpDroppedOnObject
#define MMFolder_wpEndConversation WPObject_wpEndConversation
#define MMFolder_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define MMFolder_wpFindUseItem WPObject_wpFindUseItem
#define MMFolder_wpFormatDragItem WPObject_wpFormatDragItem
#define MMFolder_wpFree WPObject_wpFree
#define MMFolder_wpFreeMem WPObject_wpFreeMem
#define MMFolder_wpHide WPObject_wpHide
#define MMFolder_wpInitData WPObject_wpInitData
#define MMFolder_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define MMFolder_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define MMFolder_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define MMFolder_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define MMFolder_wpMoveObject WPObject_wpMoveObject
#define MMFolder_wpPrintObject WPObject_wpPrintObject
#define MMFolder_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define MMFolder_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define MMFolder_wpQueryConfirmations WPObject_wpQueryConfirmations
#define MMFolder_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define MMFolder_wpQueryDefaultView WPObject_wpQueryDefaultView
#define MMFolder_wpQueryDetailsData WPObject_wpQueryDetailsData
#define MMFolder_wpQueryError WPObject_wpQueryError
#define MMFolder_wpSetFolder WPObject_wpSetFolder
#define MMFolder_wpQueryFolder WPObject_wpQueryFolder
#define MMFolder_wpQueryIcon WPObject_wpQueryIcon
#define MMFolder_wpQueryIconData WPObject_wpQueryIconData
#define MMFolder_wpQueryMinWindow WPObject_wpQueryMinWindow
#define MMFolder_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define MMFolder_wpQueryStyle WPObject_wpQueryStyle
#define MMFolder_wpSetTaskRec WPObject_wpSetTaskRec
#define MMFolder_wpFindTaskRec WPObject_wpFindTaskRec
#define MMFolder_wpQueryTitle WPObject_wpQueryTitle
#define MMFolder_wpRegisterView WPObject_wpRegisterView
#define MMFolder_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define MMFolder_wpRender WPObject_wpRender
#define MMFolder_wpRenderComplete WPObject_wpRenderComplete
#define MMFolder_wpReplaceObject WPObject_wpReplaceObject
#define MMFolder_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define MMFolder_wpRestore WPObject_wpRestore
#define MMFolder_wpRestoreData WPObject_wpRestoreData
#define MMFolder_wpRestoreLong WPObject_wpRestoreLong
#define MMFolder_wpRestoreString WPObject_wpRestoreString
#define MMFolder_wpSaveData WPObject_wpSaveData
#define MMFolder_wpSaveImmediate WPObject_wpSaveImmediate
#define MMFolder_wpSaveDeferred WPObject_wpSaveDeferred
#define MMFolder_wpSaveLong WPObject_wpSaveLong
#define MMFolder_wpSaveString WPObject_wpSaveString
#define MMFolder_wpScanSetupString WPObject_wpScanSetupString
#define MMFolder_wpSetConcurrentView WPObject_wpSetConcurrentView
#define MMFolder_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define MMFolder_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define MMFolder_wpSetDefaultView WPObject_wpSetDefaultView
#define MMFolder_wpSetError WPObject_wpSetError
#define MMFolder_wpSetIconHandle WPObject_wpSetIconHandle
#define MMFolder_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define MMFolder_wpSetupOnce WPObject_wpSetupOnce
#define MMFolder_wpSetIcon WPObject_wpSetIcon
#define MMFolder_wpSetIconData WPObject_wpSetIconData
#define MMFolder_wpSetMinWindow WPObject_wpSetMinWindow
#define MMFolder_wpSetStyle WPObject_wpSetStyle
#define MMFolder_wpModifyStyle WPObject_wpModifyStyle
#define MMFolder_wpSetTitle WPObject_wpSetTitle
#define MMFolder_wpSetup WPObject_wpSetup
#define MMFolder_wpSwitchTo WPObject_wpSwitchTo
#define MMFolder_wpUnInitData WPObject_wpUnInitData
#define MMFolder_wpViewObject WPObject_wpViewObject
#define MMFolder_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define MMFolder_wpQueryHandle WPObject_wpQueryHandle
#define MMFolder_wpUnlockObject WPObject_wpUnlockObject
#define MMFolder_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define MMFolder_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define MMFolder_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define MMFolder_wpIsDeleteable WPObject_wpIsDeleteable
#define MMFolder_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define MMFolder_wpSetObjectID WPObject_wpSetObjectID
#define MMFolder_wpQueryObjectID WPObject_wpQueryObjectID
#define MMFolder_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define MMFolder_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define MMFolder_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define MMFolder_wpFindViewItem WPObject_wpFindViewItem
#define MMFolder_wpLockObject WPObject_wpLockObject
#define MMFolder_wpIsLocked WPObject_wpIsLocked
#define MMFolder_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define MMFolder_wpWaitForClose WPObject_wpWaitForClose
#define MMFolder_somDefaultInit SOMObject_somDefaultInit
#define MMFolder_somDestruct SOMObject_somDestruct
#define MMFolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define MMFolder_somDefaultAssign SOMObject_somDefaultAssign
#define MMFolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define MMFolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define MMFolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define MMFolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define MMFolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define MMFolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define MMFolder_somInit SOMObject_somInit
#define MMFolder_somFree SOMObject_somFree
#define MMFolder_somUninit SOMObject_somUninit
#define MMFolder_somGetClass SOMObject_somGetClass
#define MMFolder_somGetClassName SOMObject_somGetClassName
#define MMFolder_somGetSize SOMObject_somGetSize
#define MMFolder_somIsA SOMObject_somIsA
#define MMFolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define MMFolder_somRespondsTo SOMObject_somRespondsTo
#define MMFolder_somDispatch SOMObject_somDispatch
#define MMFolder_somClassDispatch SOMObject_somClassDispatch
#define MMFolder_somCastObj SOMObject_somCastObj
#define MMFolder_somResetObj SOMObject_somResetObj
#define MMFolder_somDispatchV SOMObject_somDispatchV
#define MMFolder_somDispatchL SOMObject_somDispatchL
#define MMFolder_somDispatchA SOMObject_somDispatchA
#define MMFolder_somDispatchD SOMObject_somDispatchD
#define MMFolder_somPrintSelf SOMObject_somPrintSelf
#define MMFolder_somDumpSelf SOMObject_somDumpSelf
#define MMFolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_MMFolder_h */

#ifndef SOM_M_MMFolder_h
#define SOM_M_MMFolder_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_MMFolder
#define M_MMFolder SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_MMFolder_MajorVersion 1
#define M_MMFolder_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_MMFolderNewClass mmfldrMc
#pragma linkage(mmfldrMc, system)
#define M_MMFolderClassData mmfldrMd
#define M_MMFolderCClassData mmfldrMx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_MMFolder_classObj M_MMFolderClassData.classObject
#define _M_MMFolder M_MMFolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_MMFolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_MMFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_MMFolderClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_MMFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_MMFolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_MMFolderCClassData;

/*
 * New and Renew macros for M_MMFolder
 */
#define M_MMFolderNew() \
   (_somNew(_M_MMFolder ? _M_MMFolder : M_MMFolderNewClass(M_MMFolder_MajorVersion, M_MMFolder_MinorVersion)))
#define M_MMFolderRenew(buf) \
   (_somRenew(_M_MMFolder ? _M_MMFolder : M_MMFolderNewClass(M_MMFolder_MajorVersion, M_MMFolder_MinorVersion), buf))

/*
 * Override method: wpclsQueryTitle
 */
#define M_MMFolder_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_MMFolder_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryIconDataN
 */
#define M_MMFolder_wpclsQueryIconDataN(somSelf,pIconInfo,ulIconIndex) \
	M_WPFolder_wpclsQueryIconDataN(somSelf,pIconInfo,ulIconIndex)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_MMFolder_wpclsQueryIconN M_WPFolder_wpclsQueryIconN
#define M_MMFolder_wpclsQueryOpenFolders M_WPFolder_wpclsQueryOpenFolders
#define M_MMFolder_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_MMFolder_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_MMFolder_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_MMFolder_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_MMFolder_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_MMFolder_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_MMFolder_wpclsInitData M_WPObject_wpclsInitData
#define M_MMFolder_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_MMFolder_wpclsNew M_WPObject_wpclsNew
#define M_MMFolder_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_MMFolder_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_MMFolder_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_MMFolder_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_MMFolder_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_MMFolder_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_MMFolder_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_MMFolder_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_MMFolder_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_MMFolder_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_MMFolder_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_MMFolder_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_MMFolder_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_MMFolder_wpclsSetError M_WPObject_wpclsSetError
#define M_MMFolder_wpclsQueryError M_WPObject_wpclsQueryError
#define M_MMFolder_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_MMFolder_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_MMFolder_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_MMFolder_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_MMFolder_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_MMFolder_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_MMFolder_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_MMFolder_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_MMFolder_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_MMFolder_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_MMFolder_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_MMFolder_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_MMFolder__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_MMFolder__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_MMFolder__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_MMFolder__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_MMFolder_somNew SOMClass_somNew
#define M_MMFolder_somNewNoInit SOMClass_somNewNoInit
#define M_MMFolder_somRenew SOMClass_somRenew
#define M_MMFolder_somRenewNoInit SOMClass_somRenewNoInit
#define M_MMFolder_somRenewNoZero SOMClass_somRenewNoZero
#define M_MMFolder_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_MMFolder_somAllocate SOMClass_somAllocate
#define M_MMFolder_somDeallocate SOMClass_somDeallocate
#define M_MMFolder__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_MMFolder__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_MMFolder_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_MMFolder_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_MMFolder_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_MMFolder_somInitClass SOMClass_somInitClass
#define M_MMFolder_somInitMIClass SOMClass_somInitMIClass
#define M_MMFolder_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_MMFolder_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_MMFolder_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_MMFolder_somClassReady SOMClass_somClassReady
#define M_MMFolder_somGetApplyStub SOMClass_somGetApplyStub
#define M_MMFolder_somGetClassData SOMClass_somGetClassData
#define M_MMFolder_somSetClassData SOMClass_somSetClassData
#define M_MMFolder_somGetClassMtab SOMClass_somGetClassMtab
#define M_MMFolder_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_MMFolder_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_MMFolder_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_MMFolder_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_MMFolder_somGetMemberToken SOMClass_somGetMemberToken
#define M_MMFolder_somGetMethodData SOMClass_somGetMethodData
#define M_MMFolder_somGetRdStub SOMClass_somGetRdStub
#define M_MMFolder_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_MMFolder_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_MMFolder_somGetMethodToken SOMClass_somGetMethodToken
#define M_MMFolder_somGetName SOMClass_somGetName
#define M_MMFolder_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_MMFolder_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_MMFolder_somGetNumMethods SOMClass_somGetNumMethods
#define M_MMFolder_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_MMFolder_somGetParent SOMClass_somGetParent
#define M_MMFolder_somGetParents SOMClass_somGetParents
#define M_MMFolder_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_MMFolder_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_MMFolder_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_MMFolder_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_MMFolder_somFindMethod SOMClass_somFindMethod
#define M_MMFolder_somFindMethodOk SOMClass_somFindMethodOk
#define M_MMFolder_somFindSMethod SOMClass_somFindSMethod
#define M_MMFolder_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_MMFolder_somLookupMethod SOMClass_somLookupMethod
#define M_MMFolder_somCheckVersion SOMClass_somCheckVersion
#define M_MMFolder_somDescendedFrom SOMClass_somDescendedFrom
#define M_MMFolder_somSupportsMethod SOMClass_somSupportsMethod
#define M_MMFolder_somDefinedMethod SOMClass_somDefinedMethod
#define M_MMFolder_somOverrideMtab SOMClass_somOverrideMtab
#define M_MMFolder_somDefaultInit SOMObject_somDefaultInit
#define M_MMFolder_somDestruct SOMObject_somDestruct
#define M_MMFolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_MMFolder_somDefaultAssign SOMObject_somDefaultAssign
#define M_MMFolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_MMFolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_MMFolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_MMFolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_MMFolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_MMFolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_MMFolder_somInit SOMObject_somInit
#define M_MMFolder_somFree SOMObject_somFree
#define M_MMFolder_somUninit SOMObject_somUninit
#define M_MMFolder_somGetClass SOMObject_somGetClass
#define M_MMFolder_somGetClassName SOMObject_somGetClassName
#define M_MMFolder_somGetSize SOMObject_somGetSize
#define M_MMFolder_somIsA SOMObject_somIsA
#define M_MMFolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_MMFolder_somRespondsTo SOMObject_somRespondsTo
#define M_MMFolder_somDispatch SOMObject_somDispatch
#define M_MMFolder_somClassDispatch SOMObject_somClassDispatch
#define M_MMFolder_somCastObj SOMObject_somCastObj
#define M_MMFolder_somResetObj SOMObject_somResetObj
#define M_MMFolder_somDispatchV SOMObject_somDispatchV
#define M_MMFolder_somDispatchL SOMObject_somDispatchL
#define M_MMFolder_somDispatchA SOMObject_somDispatchA
#define M_MMFolder_somDispatchD SOMObject_somDispatchD
#define M_MMFolder_somPrintSelf SOMObject_somPrintSelf
#define M_MMFolder_somDumpSelf SOMObject_somDumpSelf
#define M_MMFolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_MMFolder_h */
