# Makefile

OBJECTS	= 

all:
	cd ../. && make

clean:
	-cd ./c_audio && make clean
	-cd ./c_video && make clean
	-cd ./c_image && make clean
	-cd ./c_mm && make clean
	-cd ./c_common && make clean

