/*
 * (C) Chris Wohlgemuth 2002-2004
 *
 */
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
/*
 * If you need another license for your project/product contact me at
 * 
 * http://www.os2world.com/cdwriting
 * http://www.geocities.com/SiliconValley/Sector/5785/
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwmidi_Source
#define SOM_Module_cwmidi_Source
#endif
#define CWMIDI_Class_Source
#define M_CWMIDI_Class_Source

#define INCL_PM
#include <os2.h>
#include <stdio.h>
#include "helpid.h"
#include "cwmidi.ih"
#include "cwaudioinc.h"
#include "sys_funcs.h"

extern char chrHelpLibrary[CCHMAXPATH];
extern BOOL globalHaveTimidity;

HMODULE queryResModuleHandle(void);
HMODULE queryModuleHandle(void);
BOOL getMessage(char* text,ULONG ulID, LONG lSizeText, HMODULE hResource,HWND hwnd);
BOOL mmclsCreateTheDefaultTemplate(M_WPObject *somSelf, 
                                   WPObject* Folder);


/*
 * The prototype for cwmidi_wpModifyPopupMenu was replaced by the following prototype:
 */
SOM_Scope BOOL  SOMLINK cwmidi_wpModifyPopupMenu(MMMIDI *somSelf, 
                                                 HWND hwndMenu, 
                                                 HWND hwndCnr, 
                                                 ULONG iPosition)
{
  BOOL bRC;
    /* CWMIDIData *somThis = CWMIDIGetData(somSelf); */
    MMMIDIMethodDebug("MMMIDI","cwmidi_wpModifyPopupMenu");
 
    bRC=(MMMIDI_parent_MMAudio_wpModifyPopupMenu(somSelf, 
                                                    hwndMenu, 
                                                    hwndCnr, 
                                                    iPosition));
    /*
      @@CHANGE 0.2.8

      Remove 'Start' menu for Midi files if Timidity is installed. Workaround
      for WPS crash. MAy be removed as soon as Timidity is fixed.

     */
    if(globalHaveTimidity)
      {
        WinSendMsg(hwndMenu, MM_DELETEITEM, MPFROM2SHORT( ID_MENU_START, TRUE), 0L);
      }
    WinSendMsg(hwndMenu, MM_DELETEITEM, MPFROM2SHORT( ID_MENU_CONVERT, FALSE), 0L);
    return bRC;
}


SOM_Scope ULONG  SOMLINK cwmidi_cwmmAddAudioInformationPage(MMMIDI *somSelf, 
                                                            HWND hwndNotebook)

{
    /* MMMIDIData *somThis = MMMIDIGetData(somSelf); */
    MMMIDIMethodDebug("MMMIDI","cwmidi_cwmmAddAudioInformationPage");

    // return (MMMIDI_parent_MMAudio_cwmmAddAudioInformationPage(somSelf, hwndNotebook)); 
    return SETTINGS_PAGE_REMOVED;
}


/*
 * SOM_Scope PSZ  SOMLINK cwmidiM_wpclsQueryInstanceType(M_CWMIDI *somSelf)
 */

/*
 * The prototype for cwmidiM_wpclsQueryInstanceType was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwmidiM_wpclsQueryInstanceType(M_MMMIDI *somSelf)
{
    /* M_CWMIDIData *somThis = M_CWMIDIGetData(somSelf); */
    M_MMMIDIMethodDebug("M_MMMIDI","cwmidiM_wpclsQueryInstanceType");

    return TYPE_MIDI;
    //    return "MIDI";
}


/*
 * SOM_Scope PSZ  SOMLINK cwmidiM_wpclsQueryInstanceFilter(M_CWMIDI *somSelf)
 */

/*
 * The prototype for cwmidiM_wpclsQueryInstanceFilter was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwmidiM_wpclsQueryInstanceFilter(M_MMMIDI *somSelf)
{
    /* M_CWMIDIData *somThis = M_CWMIDIGetData(somSelf); */
    M_MMMIDIMethodDebug("M_MMMIDI","cwmidiM_wpclsQueryInstanceFilter");

    return "*.mid";
}


/*
 * SOM_Scope BOOL  SOMLINK cwmidiM_wpclsQueryDefaultHelp(M_CWMIDI *somSelf, 
 *                                                       PULONG pHelpPanelId, 
 *                                                       PSZ pszHelpLibrary)
 */

/*
 * The prototype for cwmidiM_wpclsQueryDefaultHelp was replaced by the following prototype:
 */
SOM_Scope BOOL  SOMLINK cwmidiM_wpclsQueryDefaultHelp(M_MMMIDI *somSelf, 
                                                      PULONG pHelpPanelId, 
                                                      PSZ pszHelpLibrary)
{
    /* M_CWMIDIData *somThis = M_CWMIDIGetData(somSelf); */
    M_MMMIDIMethodDebug("M_MMMIDI","cwmidiM_wpclsQueryDefaultHelp");

    if(pHelpPanelId)
      *pHelpPanelId=MIDIFILE_HELP_PANEL;
    if(pszHelpLibrary)
      strncpy(pszHelpLibrary, chrHelpLibrary, CCHMAXPATH);
    return TRUE; 
}


/*
 * SOM_Scope PSZ  SOMLINK cwmidiM_wpclsQueryTitle(M_CWMIDI *somSelf)
 */

/*
 * The prototype for cwmidiM_wpclsQueryTitle was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwmidiM_wpclsQueryTitle(M_MMMIDI *somSelf)
{
  static char chrTitle[20]={0};
    /* M_CWMIDIData *somThis = M_CWMIDIGetData(somSelf); */
    M_MMMIDIMethodDebug("M_MMMIDI","cwmidiM_wpclsQueryTitle");
    if(chrTitle[0]==0)
      if(!getMessage(chrTitle, IDSTR_MIDITITLE, sizeof(chrTitle), queryResModuleHandle(), HWND_DESKTOP))
        strcpy(chrTitle, CLSTITLE_MIDI);

    return chrTitle;
}

/*
 * The prototype for cwmidiM_wpclsQueryIconData was replaced by the following prototype:
 */
SOM_Scope ULONG  SOMLINK cwmidiM_wpclsQueryIconData(M_MMMIDI *somSelf, 
                                                    PICONINFO pIconInfo)
{
  HMODULE hmod;
    /* M_CWMIDIData *somThis = M_CWMIDIGetData(somSelf); */
    M_MMMIDIMethodDebug("M_MMMIDI","cwmidiM_wpclsQueryIconData");

    hmod=queryModuleHandle();
    if(!hmod)
      return M_MMMIDI_parent_M_MMAudio_wpclsQueryIconData(somSelf, pIconInfo);

	if (pIconInfo)   {
      pIconInfo->fFormat = ICON_RESOURCE;
      pIconInfo->hmod    = hmod;
      pIconInfo->resid   = ID_ICONMIDIFILE;
	} /* endif */
    
	return ( sizeof(ICONINFO) );
}


SOM_Scope BOOL  SOMLINK cwmidiM_wpclsCreateDefaultTemplates(M_MMMIDI *somSelf, 
                                                            WPObject* Folder)
{
    /* M_MMMIDIData *somThis = M_MMMIDIGetData(somSelf); */
    M_MMMIDIMethodDebug("M_MMMIDI","cwmidiM_wpclsCreateDefaultTemplates");

    /* Default installation contains a MIDI IO-Proc. I'm lazy here and
     don't check if it's still installed but just create a default template. */
    mmclsCreateTheDefaultTemplate(somSelf, Folder);
    return TRUE;
    return (M_MMMIDI_parent_M_MMAudio_wpclsCreateDefaultTemplates(somSelf, 
                                                                  Folder));
}

