# Makefile for mediafolder

include ../../make.inc


all:
	cd ../. && make

mediafolder.dll:

clean:
	-cd ./createcd && make clean
	-cd ./cddb && make clean

cleaner:
	-cd ./mediafldr && make cleaner
	-cd ./m3ufolder && make cleaner
	-cd ./cdfldr && make cleaner
	-cd ./audioshadow && make cleaner
	-cd ./helper && make cleaner
	-cd ./createcd && make cleaner
	-cd ./cddb && make cleaner

distger:

disteng:

distribution:
