/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwpcx_Source
#define SOM_Module_cwpcx_Source
#endif
#define CWPCX_Class_Source
#define M_CWPCX_Class_Source

#include <os2.h>
#include "helpid.h"
#include "cwpcx.ih"

extern char chrHelpLibrary[CCHMAXPATH];

HMODULE queryModuleHandle(void);
BOOL getMessage(char* text,ULONG ulID, LONG lSizeText, HMODULE hResource,HWND hwnd);

SOM_Scope PSZ  SOMLINK cwpcxM_wpclsQueryInstanceType(M_CWPCX *somSelf)
{
    /* M_CWPCXData *somThis = M_CWPCXGetData(somSelf); */
    M_CWPCXMethodDebug("M_CWPCX","cwpcxM_wpclsQueryInstanceType");

    return "PCX";
}

SOM_Scope PSZ  SOMLINK cwpcxM_wpclsQueryInstanceFilter(M_CWPCX *somSelf)
{
    /* M_CWPCXData *somThis = M_CWPCXGetData(somSelf); */
    M_CWPCXMethodDebug("M_CWPCX","cwpcxM_wpclsQueryInstanceFilter");

    return "*.PCX";
}

SOM_Scope BOOL  SOMLINK cwpcxM_wpclsQueryDefaultHelp(M_CWPCX *somSelf, 
                                                     PULONG pHelpPanelId, 
                                                     PSZ pszHelpLibrary)
{
    /* M_CWPCXData *somThis = M_CWPCXGetData(somSelf); */
    M_CWPCXMethodDebug("M_CWPCX","cwpcxM_wpclsQueryDefaultHelp");

    if(pHelpPanelId)
      *pHelpPanelId=PCXFILE_HELP_PANEL;
    if(pszHelpLibrary)
      strncpy(pszHelpLibrary, chrHelpLibrary, CCHMAXPATH);
    return TRUE; 

    /*    return (M_CWPCX_parent_M_CWImage_wpclsQueryDefaultHelp(somSelf, 
          pHelpPanelId, 
          pszHelpLibrary));*/
}

SOM_Scope ULONG  SOMLINK cwpcxM_wpclsQueryStyle(M_CWPCX *somSelf)
{
    /* M_CWPCXData *somThis = M_CWPCXGetData(somSelf); */
    M_CWPCXMethodDebug("M_CWPCX","cwpcxM_wpclsQueryStyle");

    return (M_CWPCX_parent_M_CWImage_wpclsQueryStyle(somSelf));
}

SOM_Scope PSZ  SOMLINK cwpcxM_wpclsQueryTitle(M_CWPCX *somSelf)
{
  static char chrTitle[20]={0};
    /* M_CWPCXData *somThis = M_CWPCXGetData(somSelf); */
    M_CWPCXMethodDebug("M_CWPCX","cwpcxM_wpclsQueryTitle");

    if(chrTitle[0]==0)
      if(!getMessage(chrTitle, IDSTR_PCXTITLE, sizeof(chrTitle), queryModuleHandle(), HWND_DESKTOP))
        strcpy(chrTitle,"PCXImage.PCX");

    return chrTitle;
}

SOM_Scope ULONG  SOMLINK cwpcxM_wpclsQueryIconData(M_CWPCX *somSelf, 
                                                   PICONINFO pIconInfo)
{
    /* M_CWPCXData *somThis = M_CWPCXGetData(somSelf); */
    M_CWPCXMethodDebug("M_CWPCX","cwpcxM_wpclsQueryIconData");

	if (pIconInfo)   {
      pIconInfo->fFormat = ICON_RESOURCE;
      pIconInfo->hmod    = queryModuleHandle();
      pIconInfo->resid   = ID_ICONPCXFILE;
	} /* endif */

	return ( sizeof(ICONINFO) );

}

