/* rexx -  replace  DLL */

'replace H:\cwmm\classes\cwmm.dll D:\MMOS2\MMCLASS\CWMM.DLL'
'replace H:\cwmm\classes\Res\dll\mmres_DE.dll d:\MMOS2\MMCLASS\bin\mmres_DE.dll'
'replace H:\cwmm\classes\Res\dll\mmres_EN.dll d:\MMOS2\MMCLASS\bin\mmres_EN.dll'
'replace H:\cwmm\mediafolder\mediafolder.dll d:\MMOS2\MEDIAFLD\BIN\MEDIAFLD.DLL'
'replace H:\cwmm\mediafolder\res\obj\mediafolder_de.dll d:\MMOS2\MEDIAFLD\BIN\MFLDR_DE.DLL'
'del d:\MMOS2\MEDIAFLD\BIN\mediafld.hlp'
'copy H:\cwmm\mediafolder\help\mediafldr049.hlp d:\MMOS2\MEDIAFLD\BIN\mediafld.hlp'


'replace H:\cwmm\classes\cwmm.dll J:\MMOS2\CWMM\CWMM.DLL'
'replace H:\cwmm\mediafolder\mediafolder.dll J:\MMOS2\MEDIAFLD\BIN\MEDIAFLD.DLL'
'replace H:\cwmm\mediafolder\res\obj\mediafolder_de.dll J:\MMOS2\MEDIAFLD\BIN\MFLDR_DE.DLL'
'replace H:\cwmm\mediafolder\res\obj\mediafolder_en.dll J:\MMOS2\MEDIAFLD\BIN\MFLDR_EN.DLL'
'del J:\MMOS2\MEDIAFLD\BIN\mediafld.hlp'
'copy H:\cwmm\mediafolder\help\mediafldr049.hlp J:\MMOS2\MEDIAFLD\BIN\mediafld.hlp'

'replace H:\cwmm\classes\Res\dll\mmres_DE.dll J:\MMOS2\CWMM\bin\mmres_DE.dll'
'replace H:\cwmm\classes\Res\dll\mmres_EN.dll J:\MMOS2\CWMM\bin\mmres_EN.dll'

'del J:\MMOS2\MMCLASS\cwmm.hlp'
'copy H:\cwmm\classes\help\de\cwmm049.hlp J:\MMOS2\CWMM\cwmm.hlp'

'replace H:\cwmm\JPGPROC\source\JPEGIO.DLL j:\MMOS2\DLL\JPEGIO.DLL'

EXIT

'replace G:\Projects_working\Audio_cdcreator_050\source\res\001\cdfld001.dll E:\CD-BRENNER\ADC_048\cdfld001.dll'

'replace g:\projects_working\Audio_cdcreator_050\source\res\001\ipf\audiofolder001.hlp  d:\os2\help\aucdfldr.hlp'

'replace g:\projects_working\Audio_cdcreator_050\source\res\001\ipf\tutorial001.inf E:\CD-BRENNER\ADC_048\tutorial.inf'

'replace G:\Projects_working\Audio_cdcreator_050\source\ProgFolder\progfolder.dll d:\OS2\dll\progfldr.DLL'

EXIT

'replace G:\Projects_working\Audio_cdcreator_048\source\creator\audiofolder.dll E:\CD-Brenner\Audiocdcreator_047\AUCDFLDR.DLL'

'replace G:\Projects_working\Audio_cdcreator_048\source\res\001\cdfld001.dll E:\CD-Brenner\Audiocdcreator_047\CDFLD001.DLL'

'replace g:\projects_working\Audio_cdcreator_048\source\res\001\ipf\audiofolder001.hlp  d:\os2\help\aucdfldr.hlp'

'replace g:\projects_working\Audio_cdcreator_048\source\res\001\ipf\tutorial001.inf E:\CD-Brenner\Audiocdcreator_046\tutorial.inf'

'replace G:\Projects_working\Audio_cdcreator_048\source\ProgFolder\progfolder.dll d:\OS2\dll\progfldr.DLL'

/*'replace g:\projects_working\audiocpy\cwdisk.dll  d:\os2\dll\CWDSKTRK.DLL g:\projects_working\audiocpy\olddskdll'*/
/*
'replace g:\projects_working\audiocpy\cwmmaudio2.dll  d:\os2\dll\CWMMAUDI.DLL g:\projects_working\audiocpy\oldMMAdll'
*/

Exit;
