/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
/*
 * If you need another license for your project/product contact me at
 * 
 * http://www.os2world.com/cdwriting
 * http://www.geocities.com/SiliconValley/Sector/5785/
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwmov_Source
#define SOM_Module_cwmov_Source
#endif
#define CWMOV_Class_Source
#define M_CWMOV_Class_Source

#include <os2.h>
#include "helpid.h"
#include "cwmov.ih"

extern char chrHelpLibrary[CCHMAXPATH];

HMODULE queryModuleHandle(void);
BOOL getMessage(char* text,ULONG ulID, LONG lSizeText, HMODULE hResource,HWND hwnd);

SOM_Scope PSZ  SOMLINK cwmovM_wpclsQueryTitle(M_CWMOV *somSelf)
{
  static char chrTitle[20]={0};
    /* M_CWMOVData *somThis = M_CWMOVGetData(somSelf); */
    M_CWMOVMethodDebug("M_CWMOV","cwmovM_wpclsQueryTitle");

    if(chrTitle[0]==0)
      if(!getMessage(chrTitle, IDSTR_MOVTITLE, sizeof(chrTitle), queryModuleHandle(), HWND_DESKTOP))
        strcpy(chrTitle,"MOVVideo.MOV");
    return chrTitle;
}

SOM_Scope PSZ  SOMLINK cwmovM_wpclsQueryInstanceType(M_CWMOV *somSelf)
{
    /* M_CWMOVData *somThis = M_CWMOVGetData(somSelf); */
    M_CWMOVMethodDebug("M_CWMOV","cwmovM_wpclsQueryInstanceType");

    return "QuickTime Movie";
}

SOM_Scope PSZ  SOMLINK cwmovM_wpclsQueryInstanceFilter(M_CWMOV *somSelf)
{
    /* M_CWMOVData *somThis = M_CWMOVGetData(somSelf); */
    M_CWMOVMethodDebug("M_CWMOV","cwmovM_wpclsQueryInstanceFilter");

    return "*.MOV,*.QT";
}

SOM_Scope ULONG  SOMLINK cwmovM_wpclsQueryIconData(M_CWMOV *somSelf, 
                                                   PICONINFO pIconInfo)
{
    /* M_CWMOVData *somThis = M_CWMOVGetData(somSelf); */
    M_CWMOVMethodDebug("M_CWMOV","cwmovM_wpclsQueryIconData");


	if (pIconInfo)   {
      pIconInfo->fFormat = ICON_RESOURCE;
      pIconInfo->hmod    = queryModuleHandle();
      pIconInfo->resid   = ID_ICONMOVFILE;
	} /* endif */

	return ( sizeof(ICONINFO) );
}

SOM_Scope BOOL  SOMLINK cwmovM_wpclsQueryDefaultHelp(M_CWMOV *somSelf, 
                                                     PULONG pHelpPanelId, 
                                                     PSZ pszHelpLibrary)
{
    /* M_CWMOVData *somThis = M_CWMOVGetData(somSelf); */
    M_CWMOVMethodDebug("M_CWMOV","cwmovM_wpclsQueryDefaultHelp");

    if(pHelpPanelId)
      *pHelpPanelId=MOVFILE_HELP_PANEL;
    if(pszHelpLibrary)
      strncpy(pszHelpLibrary, chrHelpLibrary, CCHMAXPATH);
    return TRUE; 

    /*    return (M_CWMOV_parent_M_CWVideo_wpclsQueryDefaultHelp(somSelf, 
          pHelpPanelId, 
          pszHelpLibrary));*/
}

