/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
/*
 * If you need another license for your project/product contact me at
 * 
 * http://www.os2world.com/cdwriting
 * http://www.geocities.com/SiliconValley/Sector/5785/
 */
/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwvoc_Source
#define SOM_Module_cwvoc_Source
#endif
#define CWVOC_Class_Source
#define M_CWVOC_Class_Source

#include <os2.h>
#include "helpid.h"
#include "cwvoc.ih"

extern char chrHelpLibrary[CCHMAXPATH];

HMODULE queryModuleHandle(void);
BOOL getMessage(char* text,ULONG ulID, LONG lSizeText, HMODULE hResource,HWND hwnd);

SOM_Scope PSZ  SOMLINK cwvocM_wpclsQueryInstanceType(M_CWVOC *somSelf)
{
    /* M_CWVOCData *somThis = M_CWVOCGetData(somSelf); */
    M_CWVOCMethodDebug("M_CWVOC","cwvocM_wpclsQueryInstanceType");

    return "VOC";
}

SOM_Scope PSZ  SOMLINK cwvocM_wpclsQueryInstanceFilter(M_CWVOC *somSelf)
{
    /* M_CWVOCData *somThis = M_CWVOCGetData(somSelf); */
    M_CWVOCMethodDebug("M_CWVOC","cwvocM_wpclsQueryInstanceFilter");

    return "*.VOC";
}

SOM_Scope BOOL  SOMLINK cwvocM_wpclsQueryDefaultHelp(M_CWVOC *somSelf, 
                                                     PULONG pHelpPanelId, 
                                                     PSZ pszHelpLibrary)
{
    /* M_CWVOCData *somThis = M_CWVOCGetData(somSelf); */
    M_CWVOCMethodDebug("M_CWVOC","cwvocM_wpclsQueryDefaultHelp");


    if(pHelpPanelId)
      *pHelpPanelId=VOCFILE_HELP_PANEL;
    if(pszHelpLibrary)
      strncpy(pszHelpLibrary, chrHelpLibrary, CCHMAXPATH);
    return TRUE; 

    /*    return (M_CWVOC_parent_M_CWAudio_wpclsQueryDefaultHelp(somSelf, 
          pHelpPanelId, 
          pszHelpLibrary));*/
}

SOM_Scope PSZ  SOMLINK cwvocM_wpclsQueryTitle(M_CWVOC *somSelf)
{
  static char chrTitle[20]={0};
    /* M_CWVOCData *somThis = M_CWVOCGetData(somSelf); */
    M_CWVOCMethodDebug("M_CWVOC","cwvocM_wpclsQueryTitle");

    if(chrTitle[0]==0)
      if(!getMessage(chrTitle, IDSTR_VOCTITLE, sizeof(chrTitle), queryModuleHandle(), HWND_DESKTOP))
        strcpy(chrTitle,"VOCAudio.VOC");

    return chrTitle;
}

SOM_Scope ULONG  SOMLINK cwvocM_wpclsQueryIconData(M_CWVOC *somSelf, 
                                                   PICONINFO pIconInfo)
{
    /* M_CWVOCData *somThis = M_CWVOCGetData(somSelf); */
    M_CWVOCMethodDebug("M_CWVOC","cwvocM_wpclsQueryIconData");

	if (pIconInfo)   {
      pIconInfo->fFormat = ICON_RESOURCE;
      pIconInfo->hmod    = queryModuleHandle();
      pIconInfo->resid   = ID_ICONVOCFILE;
	} /* endif */

	return ( sizeof(ICONINFO) );
}

