

:h1 res=1000
width=30%
.支援的方法
:p.
以下是目前支援的方法。
:p.
.br
:link reftype=hd res=1010 dependent.cwGetFileSystemObject:elink.
.br
:link reftype=hd res=1040 dependent.cwPauseAudioFile:elink.
.br
:link reftype=hd res=1050 dependent.cwPlayAudioFile:elink.
.br
:link reftype=hd res=1060 dependent.cwQueryCurrentlyPlayingObject:elink.
.br
:link reftype=hd res=1090 dependent.cwSetStatusLineText:elink.
.br
:link reftype=hd res=1100 dependent.cwStopAudioFile:elink.
.br
:link reftype=hd res=1070 dependent.cwmmQueryTrackInfo:elink.
.br
:link reftype=hd res=1080 dependent.cwmmQueryImageInfo:elink.


.im newmethods.inc













