/*
 * (C) Chris Wohlgemuth 2002-2004
 *
 */
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */          
/*
 * If you need another license for your project/product (commercial,
 * noncommercial, whatever) contact me at
 * 
 * http://www.os2world.com/cdwriting
 * http://www.geocities.com/SiliconValley/Sector/5785/
 *
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwavc_Source
#define SOM_Module_cwavc_Source
#endif
#define CWAVC_Class_Source
#define M_CWAVC_Class_Source

#include <os2.h>
#include "helpid.h"
#include "cwavc.ih"

extern char chrHelpLibrary[CCHMAXPATH];

HMODULE queryResModuleHandle(void);
HMODULE queryModuleHandle(void);
BOOL getMessage(char* text,ULONG ulID, LONG lSizeText, HMODULE hResource,HWND hwnd);

/*
 * The prototype for cwavcM_wpclsQueryInstanceType was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwavcM_wpclsQueryInstanceType(M_MMAVC *somSelf)
{
    /* M_CWAVCData *somThis = M_CWAVCGetData(somSelf); */
    M_MMAVCMethodDebug("M_MMAVC","cwavcM_wpclsQueryInstanceType");

    return "AVC Image";
}

/*
 * The prototype for cwavcM_wpclsQueryInstanceFilter was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwavcM_wpclsQueryInstanceFilter(M_MMAVC *somSelf)
{
    /* M_CWAVCData *somThis = M_CWAVCGetData(somSelf); */
    M_MMAVCMethodDebug("M_MMAVC","cwavcM_wpclsQueryInstanceFilter");

    return "*._IM";
}

/*
 * The prototype for cwavcM_wpclsQueryDefaultHelp was replaced by the following prototype:
 */
SOM_Scope BOOL  SOMLINK cwavcM_wpclsQueryDefaultHelp(M_MMAVC *somSelf, 
                                                     PULONG pHelpPanelId, 
                                                     PSZ pszHelpLibrary)
{
    /* M_CWAVCData *somThis = M_CWAVCGetData(somSelf); */
    M_MMAVCMethodDebug("M_MMAVC","cwavcM_wpclsQueryDefaultHelp");

    if(pHelpPanelId)
      *pHelpPanelId=AVCFILE_HELP_PANEL;
    if(pszHelpLibrary)
      strncpy(pszHelpLibrary, chrHelpLibrary, CCHMAXPATH);
    return TRUE; 
}


/*
 * The prototype for cwavcM_wpclsQueryTitle was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwavcM_wpclsQueryTitle(M_MMAVC *somSelf)
{
  static char chrTitle[20]={0};
    /* M_CWAVCData *somThis = M_CWAVCGetData(somSelf); */
    M_MMAVCMethodDebug("M_MMAVC","cwavcM_wpclsQueryTitle");

    if(chrTitle[0]==0)
      if(!getMessage(chrTitle, IDSTR_AVCTITLE, sizeof(chrTitle), queryResModuleHandle(), HWND_DESKTOP))
        strcpy(chrTitle,"AVCImage.AVC");

    return chrTitle;
}

/*
 * The prototype for cwavcM_wpclsQueryIconData was replaced by the following prototype:
 */
SOM_Scope ULONG  SOMLINK cwavcM_wpclsQueryIconData(M_MMAVC *somSelf, 
                                                   PICONINFO pIconInfo)
{
  HMODULE hmod;

    /* M_CWAVCData *somThis = M_CWAVCGetData(somSelf); */
    M_MMAVCMethodDebug("M_MMAVC","cwavcM_wpclsQueryIconData");

    hmod=queryModuleHandle();
    if(!hmod)
      return M_MMAVC_parent_M_MMImage_wpclsQueryIconData(somSelf, pIconInfo);

	if (pIconInfo)   {
      pIconInfo->fFormat = ICON_RESOURCE;
      pIconInfo->hmod    = hmod;
      pIconInfo->resid   = ID_ICONAVCFILE;
	} /* endif */

	return ( sizeof(ICONINFO) );
}



