/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwpcx_Source
#define SOM_Module_cwpcx_Source
#endif
#define CWPCX_Class_Source
#define M_CWPCX_Class_Source

#include <os2.h>
#include "helpid.h"
#include "cwpcx.ih"

extern char chrHelpLibrary[CCHMAXPATH];

HMODULE queryResModuleHandle(void);
HMODULE queryModuleHandle(void);
BOOL getMessage(char* text,ULONG ulID, LONG lSizeText, HMODULE hResource,HWND hwnd);

/*
 * The prototype for cwpcxM_wpclsQueryInstanceType was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwpcxM_wpclsQueryInstanceType(M_MMPCX *somSelf)
{
    /* M_CWPCXData *somThis = M_CWPCXGetData(somSelf); */
    M_MMPCXMethodDebug("M_MMPCX","cwpcxM_wpclsQueryInstanceType");

    return "PCX";
}

/*
 * The prototype for cwpcxM_wpclsQueryInstanceFilter was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwpcxM_wpclsQueryInstanceFilter(M_MMPCX *somSelf)
{
    /* M_CWPCXData *somThis = M_CWPCXGetData(somSelf); */
    M_MMPCXMethodDebug("M_MMPCX","cwpcxM_wpclsQueryInstanceFilter");

    return "*.PCX";
}


/*
 * The prototype for cwpcxM_wpclsQueryDefaultHelp was replaced by the following prototype:
 */
SOM_Scope BOOL  SOMLINK cwpcxM_wpclsQueryDefaultHelp(M_MMPCX *somSelf, 
                                                     PULONG pHelpPanelId, 
                                                     PSZ pszHelpLibrary)
{
    /* M_CWPCXData *somThis = M_CWPCXGetData(somSelf); */
    M_MMPCXMethodDebug("M_MMPCX","cwpcxM_wpclsQueryDefaultHelp");

    if(pHelpPanelId)
      *pHelpPanelId=PCXFILE_HELP_PANEL;
    if(pszHelpLibrary)
      strncpy(pszHelpLibrary, chrHelpLibrary, CCHMAXPATH);
    return TRUE; 
}

/*
 * The prototype for cwpcxM_wpclsQueryTitle was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwpcxM_wpclsQueryTitle(M_MMPCX *somSelf)
{
  static char chrTitle[20]={0};
    /* M_CWPCXData *somThis = M_CWPCXGetData(somSelf); */
    M_MMPCXMethodDebug("M_MMPCX","cwpcxM_wpclsQueryTitle");

    if(chrTitle[0]==0)
      if(!getMessage(chrTitle, IDSTR_PCXTITLE, sizeof(chrTitle), queryResModuleHandle(), HWND_DESKTOP))
        strcpy(chrTitle,"PCXImage.PCX");

    return chrTitle;
}

/*
 * The prototype for cwpcxM_wpclsQueryIconData was replaced by the following prototype:
 */
SOM_Scope ULONG  SOMLINK cwpcxM_wpclsQueryIconData(M_MMPCX *somSelf, 
                                                   PICONINFO pIconInfo)
{
  HMODULE hmod;
    /* M_CWPCXData *somThis = M_CWPCXGetData(somSelf); */
    M_MMPCXMethodDebug("M_MMPCX","cwpcxM_wpclsQueryIconData");

    hmod=queryModuleHandle();
    if(!hmod)
      return M_MMPCX_parent_M_MMImage_wpclsQueryIconData(somSelf, pIconInfo);

	if (pIconInfo)   {
      pIconInfo->fFormat = ICON_RESOURCE;
      pIconInfo->hmod    = hmod;
      pIconInfo->resid   = ID_ICONPCXFILE;
	} /* endif */

	return ( sizeof(ICONINFO) );

}

