/*
 * (C) Chris Wohlgemuth 2002-2004
 *
 */
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */          
/*
 * If you need another license for your project/product (commercial,
 * noncommercial, whatever) contact me at
 * 
 * http://www.os2world.com/cdwriting
 * http://www.geocities.com/SiliconValley/Sector/5785/
 *
 */
/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwtga_Source
#define SOM_Module_cwtga_Source
#endif
#define CWTarga_Class_Source
#define M_CWTarga_Class_Source

#include <os2.h>
#include "helpid.h"
#include "cwtga.ih"

extern char chrHelpLibrary[CCHMAXPATH];

HMODULE queryResModuleHandle(void);
HMODULE queryModuleHandle(void);
BOOL getMessage(char* text,ULONG ulID, LONG lSizeText, HMODULE hResource,HWND hwnd);


/*
 * The prototype for cwtgaM_wpclsQueryInstanceType was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwtgaM_wpclsQueryInstanceType(M_MMTarga *somSelf)
{
    /* M_CWTargaData *somThis = M_CWTargaGetData(somSelf); */
    M_MMTargaMethodDebug("M_MMTarga","cwtgaM_wpclsQueryInstanceType");

    return "Targa";
}

/*
 * The prototype for cwtgaM_wpclsQueryInstanceFilter was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwtgaM_wpclsQueryInstanceFilter(M_MMTarga *somSelf)
{
    /* M_CWTargaData *somThis = M_CWTargaGetData(somSelf); */
    M_MMTargaMethodDebug("M_MMTarga","cwtgaM_wpclsQueryInstanceFilter");

    return "*.TGA";
}

/*
 * The prototype for cwtgaM_wpclsQueryDefaultHelp was replaced by the following prototype:
 */
SOM_Scope BOOL  SOMLINK cwtgaM_wpclsQueryDefaultHelp(M_MMTarga *somSelf, 
                                                     PULONG pHelpPanelId, 
                                                     PSZ pszHelpLibrary)
{
    /* M_CWTargaData *somThis = M_CWTargaGetData(somSelf); */
    M_MMTargaMethodDebug("M_MMTarga","cwtgaM_wpclsQueryDefaultHelp");

    if(pHelpPanelId)
      *pHelpPanelId=TARGAFILE_HELP_PANEL;
    if(pszHelpLibrary)
      strncpy(pszHelpLibrary, chrHelpLibrary, CCHMAXPATH);
    return TRUE; 
}

/*
 * The prototype for cwtgaM_wpclsQueryTitle was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwtgaM_wpclsQueryTitle(M_MMTarga *somSelf)
{
  static char chrTitle[20]={0};
    /* M_CWTargaData *somThis = M_CWTargaGetData(somSelf); */
    M_MMTargaMethodDebug("M_MMTarga","cwtgaM_wpclsQueryTitle");

    if(chrTitle[0]==0)
      if(!getMessage(chrTitle, IDSTR_TGATITLE, sizeof(chrTitle), queryResModuleHandle(), HWND_DESKTOP))
        strcpy(chrTitle,"TargaImage.TGA");

    return chrTitle;
}

/*
 * The prototype for cwtgaM_wpclsQueryIconData was replaced by the following prototype:
 */
SOM_Scope ULONG  SOMLINK cwtgaM_wpclsQueryIconData(M_MMTarga *somSelf, 
                                                   PICONINFO pIconInfo)
{
  HMODULE hmod;
    /* M_CWTargaData *somThis = M_CWTargaGetData(somSelf); */
    M_MMTargaMethodDebug("M_MMTarga","cwtgaM_wpclsQueryIconData");

    hmod=queryModuleHandle();
    if(!hmod)
      return M_MMTarga_parent_M_MMImage_wpclsQueryIconData(somSelf, pIconInfo);

	if (pIconInfo)   {
      pIconInfo->fFormat = ICON_RESOURCE;
      pIconInfo->hmod    = hmod;
      pIconInfo->resid   = ID_ICONTGAFILE;
	} /* endif */

	return ( sizeof(ICONINFO) );
}

