
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
/*
 * If you need another license for your project/product contact me at
 * 
 * http://www.os2world.com/cdwriting
 * http://www.geocities.com/SiliconValley/Sector/5785/
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwcdtrack_Source
#define SOM_Module_cwcdtrack_Source
#endif
#define CWCDTrack_Class_Source
#define M_CWCDTrack_Class_Source

#define INCL_PM
#define INCL_DOS
#define INCL_DOSERRORS

#include "os2.h"
#include <stdio.h>
#include "cwaudio.ih"
#include "cwcdtrack.ih"

#define IDINFO_TRACKNUM  100
#define SETUP_CDTRKTRACKNUM "CWCDTTRACKNUM"
#define CDTRACK_HELP_PANEL   30

PSZ _queryMp3HelpLibraryName(void);

SOM_Scope ULONG  SOMLINK cwcdtrack_wpQueryFileSize(CWCDTrack *somSelf)
{
    CWAudioData *somThis = CWAudioGetData(somSelf);
    /*    CWCDTrackData *somThis = CWCDTrackGetData(somSelf);*/
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_wpQueryFileSize");

    return (_ulPlaySecs*44100*4);
}

SOM_Scope BOOL  SOMLINK cwcdtrack_wpSetupOnce(CWCDTrack *somSelf, 
                                              PSZ pszSetupString)
{
  BOOL rc;
  char buffer[CCHMAXPATH];
  ULONG bufferSize;

    CWAudioData *somThis = CWAudioGetData(somSelf);
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_wpSetupOnce");

    _ulBPS=16;
    _ulChannels=2;
    _ulSampleRate=44100;
#if 0
    _ulPlaySecs=0;
    sprintf(_chrPlayTime, "%02d:%02d",_ulPlaySecs/60, _ulPlaySecs%60);
#endif
    sprintf(_chrBPS, "%d",_ulBPS);
    sprintf(_chrChannels, "%d",_ulChannels);
    sprintf(_chrSampleRate, "%d",_ulSampleRate);

    bufferSize=sizeof(buffer); 
    if(_wpScanSetupString(somSelf, pszSetupString, SETUP_CDTRKTRACKNUM, buffer, &bufferSize))
      {
        ULONG ulTrack=atoi(buffer);
        CWCDTrackData *somThis = CWCDTrackGetData(somSelf);
        if(ulTrack>0 && ulTrack<100) {
          _ulTrackNum=ulTrack;
          _wpCnrRefreshDetails(somSelf);
        }
      }
    rc=(CWCDTrack_parent_CWAudio_wpSetupOnce(somSelf, pszSetupString));
    //    _wpCnrRefreshDetails(somSelf);
    _wpSetup(somSelf, "DEFAULTVIEW=SETTINGS");

    return rc;
}


SOM_Scope BOOL  SOMLINK cwcdtrack_wpSetup(CWCDTrack *somSelf, 
                                          PSZ pszSetupString)
{
BOOL rc;
/*CWCDTrackData *somThis = CWCDTrackGetData(somSelf);*/
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_wpSetup");

   rc=(CWCDTrack_parent_CWAudio_wpSetup(somSelf, pszSetupString));

   return rc;
}

SOM_Scope ULONG  SOMLINK cwcdtrack_wpAddFileMenuPage(CWCDTrack *somSelf, 
                                                     HWND hwndNotebook)
{
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_wpAddFileMenuPage");

    return SETTINGS_PAGE_REMOVED;
}

SOM_Scope ULONG  SOMLINK cwcdtrack_wpAddFile1Page(CWCDTrack *somSelf, 
                                                  HWND hwndNotebook)
{
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_wpAddFile1Page");

    return SETTINGS_PAGE_REMOVED;
}

SOM_Scope ULONG  SOMLINK cwcdtrack_wpAddFile2Page(CWCDTrack *somSelf, 
                                                  HWND hwndNotebook)
{
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_wpAddFile2Page");

    return SETTINGS_PAGE_REMOVED;
}

SOM_Scope ULONG  SOMLINK cwcdtrack_wpAddFile3Page(CWCDTrack *somSelf, 
                                                  HWND hwndNotebook)
{
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_wpAddFile3Page");

    return SETTINGS_PAGE_REMOVED;
}

SOM_Scope ULONG  SOMLINK cwcdtrack_wpAddFileTypePage(CWCDTrack *somSelf, 
                                                     HWND hwndNotebook)
{
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_wpAddFileTypePage");

    return SETTINGS_PAGE_REMOVED;
}


SOM_Scope ULONG  SOMLINK cwcdtrack_wpFilterPopupMenu(CWCDTrack *somSelf, 
                                                     ULONG ulFlags, 
                                                     HWND hwndCnr, 
                                                     BOOL fMultiSelect)
{
  ULONG rc;

    CWCDTrackData *somThis = CWCDTrackGetData(somSelf);
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_wpFilterPopupMenu");

    rc=(CWCDTrack_parent_CWAudio_wpFilterPopupMenu(somSelf, 
                                                   ulFlags, 
                                                   hwndCnr, 
                                                   fMultiSelect));

    return (CTXT_SETTINGS | rc) & ~( CTXT_OPEN|CTXT_DELETE|CTXT_ARRANGE|CTXT_NEW|CTXT_PICKUP);
}

SOM_Scope BOOL  SOMLINK cwcdtrack_wpModifyPopupMenu(CWCDTrack *somSelf, 
                                                    HWND hwndMenu, 
                                                    HWND hwndCnr, 
                                                    ULONG iPosition)
{
  BOOL rc;
    CWCDTrackData *somThis = CWCDTrackGetData(somSelf);
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_wpModifyPopupMenu");

    rc= (CWCDTrack_parent_CWAudio_wpModifyPopupMenu(somSelf, 
                                                    hwndMenu, 
                                                    hwndCnr, 
                                                    iPosition));
    /*    WinSendMsg(hwndMenu, MM_REMOVEITEM, MPFROM2SHORT(0xBC0D, TRUE), 0);*/
    return rc;
}

SOM_Scope BOOL  SOMLINK cwcdtrack_wpInsertPopupMenuItems(CWCDTrack *somSelf, 
                                                         HWND hwndMenu, 
                                                         ULONG iPosition, 
                                                         HMODULE hmod, 
                                                         ULONG MenuID, 
                                                         ULONG SubMenuID)
{
    CWCDTrackData *somThis = CWCDTrackGetData(somSelf);
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_wpInsertPopupMenuItems");

    return (CWCDTrack_parent_CWAudio_wpInsertPopupMenuItems(somSelf, 
                                                            hwndMenu, 
                                                            iPosition, 
                                                            hmod, 
                                                            MenuID, 
                                                            SubMenuID));
}

SOM_Scope ULONG  SOMLINK cwcdtrack_cwmmQueryTrackInfo(CWCDTrack *somSelf, 
                                                      char** chrString, 
                                                      ULONG ulSize, 
                                                      int iWhich)
{
    CWCDTrackData *somThis = CWCDTrackGetData(somSelf);
    CWCDTrackMethodDebug("CWCDTrack","cwcdtrack_cwmmQueryTrackInfo");

    switch(iWhich)
      {
      case IDINFO_TRACKNUM:
        {
        return _ulTrackNum;
        }
      default:
      break;
      }
    return (CWCDTrack_parent_CWAudio_cwmmQueryTrackInfo(somSelf, 
                                                        chrString, 
                                                        ulSize, 
                                                        iWhich));
}


SOM_Scope ULONG  SOMLINK cwcdtrackM_wpclsQueryStyle(M_CWCDTrack *somSelf)
{
    /* M_CWCDTrackData *somThis = M_CWCDTrackGetData(somSelf); */
    M_CWCDTrackMethodDebug("M_CWCDTrack","cwcdtrackM_wpclsQueryStyle");

    return (M_CWCDTrack_parent_M_CWAudio_wpclsQueryStyle(somSelf)
            |CLSSTYLE_NEVERLINK|CLSSTYLE_NEVERCOPY|CLSSTYLE_NEVERMOVE|CLSSTYLE_NEVERPRINT|CLSSTYLE_DONTTEMPLATE);
}

SOM_Scope PSZ  SOMLINK cwcdtrackM_wpclsQueryTitle(M_CWCDTrack *somSelf)
{
    /* M_CWCDTrackData *somThis = M_CWCDTrackGetData(somSelf); */
    M_CWCDTrackMethodDebug("M_CWCDTrack","cwcdtrackM_wpclsQueryTitle");

    return "CDTrack";
    /*    return (M_CWCDTrack_parent_M_CWAudio_wpclsQueryTitle(somSelf)); */
}



SOM_Scope PSZ  SOMLINK cwcdtrackM_wpclsQueryInstanceType(M_CWCDTrack *somSelf)
{
    /* M_CWCDTrackData *somThis = M_CWCDTrackGetData(somSelf); */
    M_CWCDTrackMethodDebug("M_CWCDTrack","cwcdtrackM_wpclsQueryInstanceType");

    return "CDTrack";

    /*    return (M_CWCDTrack_parent_M_CWAudio_wpclsQueryInstanceType(somSelf));*/
}


/*
 *
 *    wpclsQueryInstanceFilter    : override;
 *    wpclsQueryIconData          : override;
 *
 *    wpclsInitData               : override;
 */

SOM_Scope BOOL  SOMLINK cwcdtrackM_wpclsQueryDefaultHelp(M_CWCDTrack *somSelf, 
                                                         PULONG pHelpPanelId, 
                                                         PSZ pszHelpLibrary)
{
  PSZ pszHelpLibName;
    /* M_CWCDTrackData *somThis = M_CWCDTrackGetData(somSelf); */
    M_CWCDTrackMethodDebug("M_CWCDTrack","cwcdtrackM_wpclsQueryDefaultHelp");

    if((pszHelpLibName=_queryMp3HelpLibraryName())!=NULLHANDLE)
      {
        if(pHelpPanelId)
          *pHelpPanelId=CDTRACK_HELP_PANEL;
        if(pszHelpLibrary)
          strncpy(pszHelpLibrary, pszHelpLibName, CCHMAXPATH);
        return TRUE; 
      }

    return (M_CWCDTrack_parent_M_CWAudio_wpclsQueryDefaultHelp(somSelf, 
                                                               pHelpPanelId, 
                                                               pszHelpLibrary));
}

