
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */
/*
 * If you need another license for your project/product contact me at
 * 
 * http://www.os2world.com/cdwriting
 * http://www.geocities.com/SiliconValley/Sector/5785/
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwmidi_Source
#define SOM_Module_cwmidi_Source
#endif
#define CWMIDI_Class_Source
#define M_CWMIDI_Class_Source

#define INCL_PM
#include <os2.h>
#include <stdio.h>
#include "helpid.h"
#include "cwmidi.ih"

extern char chrHelpLibrary[CCHMAXPATH];

HMODULE queryModuleHandle(void);
BOOL getMessage(char* text,ULONG ulID, LONG lSizeText, HMODULE hResource,HWND hwnd);



SOM_Scope BOOL  SOMLINK cwmidi_wpModifyPopupMenu(CWMIDI *somSelf, 
                                                 HWND hwndMenu, 
                                                 HWND hwndCnr, 
                                                 ULONG iPosition)
{
  BOOL bRC;
    /* CWMIDIData *somThis = CWMIDIGetData(somSelf); */
    CWMIDIMethodDebug("CWMIDI","cwmidi_wpModifyPopupMenu");
 
    bRC=(CWMIDI_parent_CWAudio_wpModifyPopupMenu(somSelf, 
                                                    hwndMenu, 
                                                    hwndCnr, 
                                                    iPosition));
    WinSendMsg(hwndMenu, MM_DELETEITEM, MPFROM2SHORT( ID_MENU_CONVERT, FALSE), 0L);
    return bRC;
}


SOM_Scope ULONG  SOMLINK cwmidi_cwmmAddWaveInformationPage(CWMIDI *somSelf, 
                                                           HWND hwndNotebook)
{

/*  CWMIDIData *somThis = CWMIDIGetData(somSelf);*/
    CWMIDIMethodDebug("CWMIDI","cwmidi_cwmmAddWaveInformationPage");

    return SETTINGS_PAGE_REMOVED;
}




SOM_Scope PSZ  SOMLINK cwmidiM_wpclsQueryInstanceType(M_CWMIDI *somSelf)
{
    /* M_CWMIDIData *somThis = M_CWMIDIGetData(somSelf); */
    M_CWMIDIMethodDebug("M_CWMIDI","cwmidiM_wpclsQueryInstanceType");

    return "MIDI";
}

SOM_Scope PSZ  SOMLINK cwmidiM_wpclsQueryInstanceFilter(M_CWMIDI *somSelf)
{
    /* M_CWMIDIData *somThis = M_CWMIDIGetData(somSelf); */
    M_CWMIDIMethodDebug("M_CWMIDI","cwmidiM_wpclsQueryInstanceFilter");

    return "*.mid";
}

SOM_Scope BOOL  SOMLINK cwmidiM_wpclsQueryDefaultHelp(M_CWMIDI *somSelf, 
                                                      PULONG pHelpPanelId, 
                                                      PSZ pszHelpLibrary)
{
    /* M_CWMIDIData *somThis = M_CWMIDIGetData(somSelf); */
    M_CWMIDIMethodDebug("M_CWMIDI","cwmidiM_wpclsQueryDefaultHelp");

    if(pHelpPanelId)
      *pHelpPanelId=MIDIFILE_HELP_PANEL;
    if(pszHelpLibrary)
      strncpy(pszHelpLibrary, chrHelpLibrary, CCHMAXPATH);
    return TRUE; 

    /*    return (M_CWMIDI_parent_M_CWAudio_wpclsQueryDefaultHelp(somSelf, 
          pHelpPanelId, 
          pszHelpLibrary));*/
}

SOM_Scope PSZ  SOMLINK cwmidiM_wpclsQueryTitle(M_CWMIDI *somSelf)
{
  static char chrTitle[20]={0};
    /* M_CWMIDIData *somThis = M_CWMIDIGetData(somSelf); */
    M_CWMIDIMethodDebug("M_CWMIDI","cwmidiM_wpclsQueryTitle");
    if(chrTitle[0]==0)
      if(!getMessage(chrTitle, IDSTR_MIDITITLE, sizeof(chrTitle), queryModuleHandle(), HWND_DESKTOP))
        strcpy(chrTitle,"MIDI.MID");

    return chrTitle;
}

SOM_Scope ULONG  SOMLINK cwmidiM_wpclsQueryIconData(M_CWMIDI *somSelf, 
                                                    PICONINFO pIconInfo)
{
    /* M_CWMIDIData *somThis = M_CWMIDIGetData(somSelf); */
    M_CWMIDIMethodDebug("M_CWMIDI","cwmidiM_wpclsQueryIconData");

	if (pIconInfo)   {
      pIconInfo->fFormat = ICON_RESOURCE;
      pIconInfo->hmod    = queryModuleHandle();
      pIconInfo->resid   = ID_ICONMIDIFILE;
	} /* endif */
    
	return ( sizeof(ICONINFO) );
}

