
/*
 *  This file was generated by the SOM Compiler.
 *  Generated using:
 *     SOM incremental update: 2.42
 */


/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwbmp_Source
#define SOM_Module_cwbmp_Source
#endif
#define CWBitmap_Class_Source
#define M_CWBitmap_Class_Source

#define INCL_DOS
#define INCL_PM
#include <os2.h>
#include <stdio.h>

#include "cwbmp.ih"
#include "except.h"
#include "cwmmres.h"
#include "cwaudioinc.h"

#define STR_BITMAPNAME   "Bitmap"

extern LONG  lNumIOProcs;

HMODULE queryModuleHandle(void);
BOOL insertIOProcMenuItems( HWND hwndMenu );
ULONG launchPMProg(PSZ pszTitle, PSZ wrapperExe, PSZ parameters,  WPObject *thisPtr, ULONG ulView);
BOOL getMessage(char* text,ULONG ulID, LONG lSizeText, HMODULE hResource,HWND hwnd);
BOOL getBmpInfoHeader(PBITMAPINFOHEADER2  bmpih2, PSZ pszFileName, char* procName, ULONG ulLength);
HBITMAP loadBitmap ( PSZ pszFileName, PBITMAPINFOHEADER2 pBMPInfoHeader2);
HBITMAP createNewBitmap ( HBITMAP hbm,
                          PBITMAPINFOHEADER2 pBmpInfoHeader2,
                          ULONG ulWidth, 
                          ULONG ulHeight, 
                          BOOL* pbQuitEarly);

MRESULT EXPENTRY bmpInfoDlgProc(HWND hwnd, ULONG msg, MPARAM mp1, MPARAM mp2)
{
  CWBitmap *cwImage;

  switch(msg) {
  case WM_INITDLG :
    cwImage=(CWBitmap*)LONGFROMMP(mp2);
    if(somIsObj(cwImage)) {
      //      CWBitmapData *somThis = CWBitmapGetData(cwImage);

      PBITMAPINFOHEADER2 pbmpih2;

      if((pbmpih2=(PBITMAPINFOHEADER2) _cwmmQueryBitmapInfoHeader(cwImage))!=NULLHANDLE)
        {
          char fName[CCHMAXPATH];
          char chrTemplate[100];

          if(pbmpih2->cbFix==sizeof(BITMAPINFOHEADER2)) {
            getMessage(chrTemplate, IDSTR_SPRINTFPIXEL, sizeof(chrTemplate), 
                       queryModuleHandle(), hwnd);;
            sprintf(fName, chrTemplate,pbmpih2->cx);
            WinSetWindowText(WinWindowFromID(hwnd, IDST_IMAGEWIDTH),fName);
            
            sprintf(fName, chrTemplate, pbmpih2->cy);
            WinSetWindowText(WinWindowFromID(hwnd, IDST_IMAGEHEIGHT),fName);

            getMessage(chrTemplate, IDSTR_SPRINTFBIT, sizeof(chrTemplate), 
                       queryModuleHandle(), hwnd);;            
            sprintf(fName, chrTemplate, pbmpih2->cBitCount);
            WinSetWindowText(WinWindowFromID(hwnd, IDST_COLORDEPTH),fName);
          }
          else if(pbmpih2->cbFix==sizeof(BITMAPINFOHEADER)) {
            /* We shouldn't get a BITMAPINFOHEADER here but who knows...*/
            PBITMAPINFOHEADER pbmpih=(PBITMAPINFOHEADER)pbmpih2;
            getMessage(chrTemplate, IDSTR_SPRINTFPIXEL, sizeof(chrTemplate), 
                       queryModuleHandle(), hwnd);;

            sprintf(fName, chrTemplate,pbmpih->cx);
            WinSetWindowText(WinWindowFromID(hwnd, IDST_IMAGEWIDTH),fName);
            
            sprintf(fName, chrTemplate, pbmpih->cy);
            WinSetWindowText(WinWindowFromID(hwnd, IDST_IMAGEHEIGHT),fName);

            getMessage(chrTemplate, IDSTR_SPRINTFBIT, sizeof(chrTemplate), 
                       queryModuleHandle(), hwnd);;                        
            sprintf(fName, chrTemplate, pbmpih->cBitCount);
            WinSetWindowText(WinWindowFromID(hwnd, IDST_COLORDEPTH),fName);
          }
          
          WinSetWindowText(WinWindowFromID(hwnd, IDST_IMAGEFORMAT), STR_BITMAPNAME);
        }
    }/* somIsObj() */
    return (MRESULT)TRUE;
    /* This prevents switching the notebook page behind the open folder */
    case WM_WINDOWPOSCHANGED:
      {
        MRESULT mr;

        if(WinQueryFocus(HWND_DESKTOP)!=
           WinQueryWindow(WinQueryWindow(hwnd, QW_PARENT), QW_PARENT)) {
          mp2=MPFROMLONG(LONGFROMMP(mp2)|0x80000);/*AWP_ACTIVATE 0x00080000L*/
          mr=WinDefDlgProc(hwnd, msg, mp1, mp2);
          return mr;  
        }
        break;
      }
    case WM_FOCUSCHANGE:
      {
        if(!SHORT1FROMMP(mp2)) {
          if(HWNDFROMMP(mp1)==hwnd) {
            MRESULT mr;

            mr=WinDefDlgProc(hwnd, msg, mp1, mp2);
            WinSendMsg(WinQueryWindow(WinQueryWindow(hwnd, QW_PARENT), QW_PARENT), 
                       WM_SETFOCUS, MPFROMHWND(hwnd), (MPARAM)TRUE);
            return mr;
          }
        }
        break;
      }
    case WM_DESTROY:
      /* The notebook closes and gets destroyed */
      /* Set focus to desktop to prevent PM freeze */
      WinSetFocus(HWND_DESKTOP, HWND_DESKTOP);
      break;
  default:
    break;
  }
  return WinDefDlgProc(hwnd, msg, mp1, mp2);
}

SOM_Scope ULONG  SOMLINK cwbmp_cwmmAddImageInformationPage(CWBitmap *somSelf, 
                                                           HWND hwndNotebook)
{
  PAGEINFO pageinfo;
  char pageName[100];

    /* CWBitmapData *somThis = CWBitmapGetData(somSelf); */
    CWBitmapMethodDebug("CWBitmap","cwbmp_cwmmAddImageInformationPage");

  //Clear the pageinfo structure
  memset((PCH)&pageinfo, 0, sizeof(PAGEINFO));
  //Fill the pageinfo structure
  pageinfo.cb = sizeof(PAGEINFO);
  pageinfo.hwndPage = NULLHANDLE;
  pageinfo.usPageStyleFlags = BKA_MAJOR | BKA_STATUSTEXTON;
  pageinfo.usPageInsertFlags = BKA_FIRST;
  //We want page numbers
  pageinfo.usSettingsFlags = SETTINGS_PAGE_NUMBERS;
  //The dialog procedure for this page
  pageinfo.pfnwp = bmpInfoDlgProc;
  //The resource DLL
  pageinfo.resid = queryModuleHandle();
  //pageinfo.resid = queryModuleHandle();
  //The ID of the dialog template
  pageinfo.dlgid = IDDLG_IMAGEINFOPAGE;
  //pageinfo.dlgid = IDDLG_WAVEINFOPAGE;
  //We need a pointer to our WPS-object in the dialog procedure
  //to call class functions
  pageinfo.pCreateParams = somSelf;
  //The ID of the help panel for this page
  //pageinfo.idDefaultHelpPanel = IDDLG_GENERAL2PAGE;

  //Tell the WPS the help library name
  pageinfo.pszHelpLibraryName = NULLHANDLE;
  //We have a major tab so we need a name
  /* pageName: "ISO filesystem" */
  getMessage(pageName, IDSTR_IMAGEINFOPAGENAME, sizeof(pageName),  queryModuleHandle(), hwndNotebook);
  pageinfo.pszName = pageName;
  //Insert the page into the settings notebook
  return _wpInsertSettingsPage(somSelf,hwndNotebook,&pageinfo);
}


static HBITMAP  cwQueryBitmapHandle(CWBitmap *somSelf, 
                                 ULONG ulWidth, 
                                 ULONG ulHeight)
{
  ULONG ulSize;
  char chrName[CCHMAXPATH];
  PBYTE pByte;
  BOOL bGotHeader=FALSE;
  HBITMAP hbm=NULLHANDLE;
  HBITMAP hbm2;
  
  CWBitmapData *somThis = CWBitmapGetData(somSelf); 
  //   CWImageMethodDebug("CWBitmap","cwimg_wpQueryBitmapHandle");
  
  if(ulWidth==0 || ulHeight==0)
    return NULLHANDLE;
  
  ulSize=sizeof(chrName);
  if(!_wpQueryRealName(somSelf, chrName, &ulSize,TRUE))
    return NULLHANDLE;

    
  TRY_LOUD(LOAD_BMP3) {
    if(_cwmmQueryBitmapInfoHeader(somSelf))
      bGotHeader=TRUE;
  }
  CATCH(LOAD_BMP3)
    {
#if 0
      if(MBID_OK==showMsgBox2(IDSTR_CWIMAGETITLE, IDSTR_IMGIOPROCCRASH, queryModuleHandle(),
                              MB_OK | MB_MOVEABLE | MB_WARNING))
        exit(0);
      exit(0);
#endif
    }END_CATCH;
    
    if(!bGotHeader)
      return NULLHANDLE;

    TRY_LOUD(LOAD_BMP4) {
      hbm=loadBitmap ( chrName , (PBITMAPINFOHEADER2) _pBmpInfoHeader2);
    }
    CATCH(LOAD_BMP4)
      {
#if 0
        if(MBID_OK==showMsgBox2(IDSTR_CWIMAGETITLE, IDSTR_IMGIOPROCCRASH, queryModuleHandle(),
                                MB_OK | MB_MOVEABLE | MB_WARNING))
          exit(0);
        exit(0);
#endif
        hbm=NULLHANDLE;
      } END_CATCH;
      
      if(!hbm)
        return NULLHANDLE;
      
      
    TRY_LOUD(QRY_HBM) {
      hbm2=createNewBitmap ( hbm, (PBITMAPINFOHEADER2) _pBmpInfoHeader2, ulWidth, ulHeight , NULLHANDLE);
    }
    CATCH(QRY_HBM)
      {
        hbm2=NULLHANDLE;
      } END_CATCH;
      
      GpiDeleteBitmap(hbm);
      return hbm2;
}

SOM_Scope HBITMAP  SOMLINK cwbmp_cwmmQuerySmallBitmapHandle(CWBitmap *somSelf, 
                                                            ULONG ulSize)
{
HBITMAP hbm;
    CWBitmapData *somThis = CWBitmapGetData(somSelf);
    CWBitmapMethodDebug("CWBitmap","cwbmp_cwmmQuerySmallBitmapHandle");

    if(ulSize<MAX_SIZE_SMALLBITMAP)
      ulSize=MAX_SIZE_SMALLBITMAP;

    if(ulSize>_ulSizeSmallBitmap)
      {
        if(_hBitmapSmall) {
          GpiDeleteBitmap(_hBitmapSmall);
          _hBitmapSmall=NULLHANDLE;
        }
      }

    /* Return statement to be customized: */
    return _hBitmapSmall;
}

SOM_Scope void  SOMLINK cwbmp_cwmmFreeBitmaps(CWBitmap *somSelf)
{
    CWBitmapData *somThis = CWBitmapGetData(somSelf);
    CWBitmapMethodDebug("CWBitmap","cwbmp_cwmmFreeBitmaps");

}

SOM_Scope void  SOMLINK cwbmp_cwmmFreeSmallBitmap(CWBitmap *somSelf)
{
    CWBitmapData *somThis = CWBitmapGetData(somSelf);
    CWBitmapMethodDebug("CWBitmap","cwbmp_cwmmFreeSmallBitmap");

}

SOM_Scope PBYTE  SOMLINK cwbmp_cwmmQueryBitmapInfoHeader(CWBitmap *somSelf)
{
    CWBitmapData *somThis = CWBitmapGetData(somSelf);
    CWBitmapMethodDebug("CWBitmap","cwbmp_cwmmQueryBitmapInfoHeader");


    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK cwbmp_wpModifyPopupMenu(CWBitmap *somSelf, 
                                                HWND hwndMenu, 
                                                HWND hwndCnr, 
                                                ULONG iPosition)
{
    CWBitmapData *somThis = CWBitmapGetData(somSelf);
    CWBitmapMethodDebug("CWBitmap","cwbmp_wpModifyPopupMenu");

    return (CWBitmap_parent_WPBitmap_wpModifyPopupMenu(somSelf, 
                                                       hwndMenu, 
                                                       hwndCnr, 
                                                       iPosition));
}

SOM_Scope BOOL  SOMLINK cwbmp_wpMenuItemSelected(CWBitmap *somSelf, 
                                                 HWND hwndFrame, 
                                                 ULONG ulMenuId)
{
    CWBitmapData *somThis = CWBitmapGetData(somSelf);
    CWBitmapMethodDebug("CWBitmap","cwbmp_wpMenuItemSelected");

    return (CWBitmap_parent_WPBitmap_wpMenuItemSelected(somSelf, 
                                                        hwndFrame, 
                                                        ulMenuId));
}

SOM_Scope HWND  SOMLINK cwbmp_wpOpen(CWBitmap *somSelf, HWND hwndCnr, 
                                     ULONG ulView, ULONG param)
{
    CWBitmapData *somThis = CWBitmapGetData(somSelf);
    CWBitmapMethodDebug("CWBitmap","cwbmp_wpOpen");

    return (CWBitmap_parent_WPBitmap_wpOpen(somSelf, hwndCnr, 
                                            ulView, param));
}

SOM_Scope BOOL  SOMLINK cwbmp_wpAddSettingsPages(CWBitmap *somSelf, 
                                                 HWND hwndNotebook)
{
    CWBitmapData *somThis = CWBitmapGetData(somSelf);
    CWBitmapMethodDebug("CWBitmap","cwbmp_wpAddSettingsPages");

    return (CWBitmap_parent_WPBitmap_wpAddSettingsPages(somSelf, 
                                                        hwndNotebook));
}

SOM_Scope void  SOMLINK cwbmp_wpUnInitData(CWBitmap *somSelf)
{
    CWBitmapData *somThis = CWBitmapGetData(somSelf);
    CWBitmapMethodDebug("CWBitmap","cwbmp_wpUnInitData");

    CWBitmap_parent_WPBitmap_wpUnInitData(somSelf);
}

SOM_Scope void  SOMLINK cwbmp_wpInitData(CWBitmap *somSelf)
{
    CWBitmapData *somThis = CWBitmapGetData(somSelf);
    CWBitmapMethodDebug("CWBitmap","cwbmp_wpInitData");

    CWBitmap_parent_WPBitmap_wpInitData(somSelf);
}

SOM_Scope ULONG  SOMLINK cwbmp_wpQueryDetailsData(CWBitmap *somSelf, 
                                                  PVOID* ppDetailsData, 
                                                  PULONG pcp)
{
    CWBitmapData *somThis = CWBitmapGetData(somSelf);
    CWBitmapMethodDebug("CWBitmap","cwbmp_wpQueryDetailsData");

    return (CWBitmap_parent_WPBitmap_wpQueryDetailsData(somSelf, 
                                                        ppDetailsData, 
                                                        pcp));
}


SOM_Scope ULONG  SOMLINK cwbmpM_wpclsQueryDefaultView(M_CWBitmap *somSelf)
{
    /* M_CWBitmapData *somThis = M_CWBitmapGetData(somSelf); */
    M_CWBitmapMethodDebug("M_CWBitmap","cwbmpM_wpclsQueryDefaultView");

    return (M_CWBitmap_parent_M_WPBitmap_wpclsQueryDefaultView(somSelf));
}

SOM_Scope ULONG  SOMLINK cwbmpM_wpclsQueryIconData(M_CWBitmap *somSelf, 
                                                   PICONINFO pIconInfo)
{
    /* M_CWBitmapData *somThis = M_CWBitmapGetData(somSelf); */
    M_CWBitmapMethodDebug("M_CWBitmap","cwbmpM_wpclsQueryIconData");

    return (M_CWBitmap_parent_M_WPBitmap_wpclsQueryIconData(somSelf, 
                                                            pIconInfo));
}

SOM_Scope ULONG  SOMLINK cwbmpM_wpclsQueryDetailsInfo(M_CWBitmap *somSelf, 
                                                      PCLASSFIELDINFO* ppClassFieldInfo, 
                                                      PULONG pSize)
{
    /* M_CWBitmapData *somThis = M_CWBitmapGetData(somSelf); */
    M_CWBitmapMethodDebug("M_CWBitmap","cwbmpM_wpclsQueryDetailsInfo");

    return (M_CWBitmap_parent_M_WPBitmap_wpclsQueryDetailsInfo(somSelf, 
                                                               ppClassFieldInfo, 
                                                               pSize));
}

SOM_Scope void  SOMLINK cwbmpM_wpclsInitData(M_CWBitmap *somSelf)
{
    /* M_CWBitmapData *somThis = M_CWBitmapGetData(somSelf); */
    M_CWBitmapMethodDebug("M_CWBitmap","cwbmpM_wpclsInitData");

    M_CWBitmap_parent_M_WPBitmap_wpclsInitData(somSelf);
}


/*******************************************/
