/*
 * (C) Chris Wohlgemuth 2002-2004
 *
 */
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 */          
/*
 * If you need another license for your project/product (commercial,
 * noncommercial, whatever) contact me at
 * 
 * http://www.os2world.com/cdwriting
 * http://www.geocities.com/SiliconValley/Sector/5785/
 *
 */
/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwjpg_Source
#define SOM_Module_cwjpg_Source
#endif
#define CWJPG_Class_Source
#define M_CWJPG_Class_Source

#include <os2.h>
#include "helpid.h"
#include "cwjpg.ih"
#include "cwaudioinc.h"

extern char chrHelpLibrary[CCHMAXPATH];

HMODULE queryResModuleHandle(void);
HMODULE queryModuleHandle(void);
BOOL getMessage(char* text,ULONG ulID, LONG lSizeText, HMODULE hResource,HWND hwnd);
BOOL checkImageIOProc(char * chrExt);
BOOL mmclsCreateTheDefaultTemplate(M_WPObject *somSelf, 
                                   WPObject* Folder);

/*
 * The prototype for cwjpgM_wpclsQueryInstanceType was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwjpgM_wpclsQueryInstanceType(M_MMJPG *somSelf)
{
    /* M_CWJPGData *somThis = M_CWJPGGetData(somSelf); */
    M_MMJPGMethodDebug("M_MMJPG","cwjpgM_wpclsQueryInstanceType");

    return "JPG";
}

/*
 * The prototype for cwjpgM_wpclsQueryInstanceFilter was replaced by the following prototype:
 */
/*
 *    wpclsCreateDefaultTemplates : override;
 */

SOM_Scope PSZ  SOMLINK cwjpgM_wpclsQueryInstanceFilter(M_MMJPG *somSelf)
{
    /* M_CWJPGData *somThis = M_CWJPGGetData(somSelf); */
    M_MMJPGMethodDebug("M_MMJPG","cwjpgM_wpclsQueryInstanceFilter");

    return "*.JPG";
}

#if 0
SOM_Scope BOOL  SOMLINK cwjpgM_wpclsCreateDefaultTemplates(M_MMJPG *somSelf, 
                                                           WPObject* Folder)
{
    /* M_MMJPGData *somThis = M_MMJPGGetData(somSelf); */
    M_MMJPGMethodDebug("M_MMJPG","cwjpgM_wpclsCreateDefaultTemplates");

    /* The FOURCC of the JPEG-IO proc is JPEG so we have to create the template
       here. Templates for other image files are created in MMImage. */
DosBeep(5000, 1000);
    if(checkImageIOProc( "JPEG")) {
DosBeep(500, 1000);
      mmclsCreateTheDefaultTemplate(somSelf, Folder);
      return TRUE;
    }

    return TRUE;
}
#endif
/*
 * The prototype for cwjpgM_wpclsQueryDefaultHelp was replaced by the following prototype:
 */
SOM_Scope BOOL  SOMLINK cwjpgM_wpclsQueryDefaultHelp(M_MMJPG *somSelf, 
                                                     PULONG pHelpPanelId, 
                                                     PSZ pszHelpLibrary)
{
    /* M_CWJPGData *somThis = M_CWJPGGetData(somSelf); */
    M_MMJPGMethodDebug("M_MMJPG","cwjpgM_wpclsQueryDefaultHelp");

    if(pHelpPanelId)
      *pHelpPanelId=JPGFILE_HELP_PANEL;
    if(pszHelpLibrary)
      strncpy(pszHelpLibrary, chrHelpLibrary, CCHMAXPATH);
    return TRUE; 
}

/*
 * The prototype for cwjpgM_wpclsQueryTitle was replaced by the following prototype:
 */
SOM_Scope PSZ  SOMLINK cwjpgM_wpclsQueryTitle(M_MMJPG *somSelf)
{
  static char chrTitle[20]={0};
    /* M_CWJPGData *somThis = M_CWJPGGetData(somSelf); */
    M_MMJPGMethodDebug("M_MMJPG","cwjpgM_wpclsQueryTitle");

    if(chrTitle[0]==0)
      if(!getMessage(chrTitle, IDSTR_JPGTITLE, sizeof(chrTitle), queryResModuleHandle(), HWND_DESKTOP))
        strcpy(chrTitle,"JPGImage.JPG");

    return chrTitle;
}

/*
 * The prototype for cwjpgM_wpclsQueryIconData was replaced by the following prototype:
 */
SOM_Scope ULONG  SOMLINK cwjpgM_wpclsQueryIconData(M_MMJPG *somSelf, 
                                                   PICONINFO pIconInfo)
{
  HMODULE hmod;

    /* M_CWJPGData *somThis = M_CWJPGGetData(somSelf); */
    M_MMJPGMethodDebug("M_MMJPG","cwjpgM_wpclsQueryIconData");

    hmod=queryModuleHandle();
    if(!hmod)
      return M_MMJPG_parent_M_MMImage_wpclsQueryIconData(somSelf, pIconInfo);

	if (pIconInfo)   {
      pIconInfo->fFormat = ICON_RESOURCE;
      pIconInfo->hmod    = hmod;
      pIconInfo->resid   = ID_ICONJPGFILE;
	} /* endif */

	return ( sizeof(ICONINFO) );
}








