/* rexx -  replace  DLL */



'replace H:\cwmm\classes\cwmm.dll D:\OS2\APPS\CWMMOS2\CWMM\cwmm.dll'
'replace H:\cwmm\mediafolder\mediafolder.dll D:\OS2\APPS\CWMMOS2\MediaFld\bin\mediafld.dll'
'replace H:\cwmm\mediafolder\RES\mediafolder049.dll D:\OS2\APPS\CWMMOS2\MediaFld\bin\MEDIA049.DLL'

EXIT

'replace G:\Projects_working\Audio_cdcreator_050\source\res\001\cdfld001.dll E:\CD-BRENNER\ADC_048\cdfld001.dll'

'replace g:\projects_working\Audio_cdcreator_050\source\res\001\ipf\audiofolder001.hlp  d:\os2\help\aucdfldr.hlp'

'replace g:\projects_working\Audio_cdcreator_050\source\res\001\ipf\tutorial001.inf E:\CD-BRENNER\ADC_048\tutorial.inf'

'replace G:\Projects_working\Audio_cdcreator_050\source\ProgFolder\progfolder.dll d:\OS2\dll\progfldr.DLL'

EXIT

'replace G:\Projects_working\Audio_cdcreator_048\source\creator\audiofolder.dll E:\CD-Brenner\Audiocdcreator_047\AUCDFLDR.DLL'

'replace G:\Projects_working\Audio_cdcreator_048\source\res\001\cdfld001.dll E:\CD-Brenner\Audiocdcreator_047\CDFLD001.DLL'

'replace g:\projects_working\Audio_cdcreator_048\source\res\001\ipf\audiofolder001.hlp  d:\os2\help\aucdfldr.hlp'

'replace g:\projects_working\Audio_cdcreator_048\source\res\001\ipf\tutorial001.inf E:\CD-Brenner\Audiocdcreator_046\tutorial.inf'

'replace G:\Projects_working\Audio_cdcreator_048\source\ProgFolder\progfolder.dll d:\OS2\dll\progfldr.DLL'

/*'replace g:\projects_working\audiocpy\cwdisk.dll  d:\os2\dll\CWDSKTRK.DLL g:\projects_working\audiocpy\olddskdll'*/
/*
'replace g:\projects_working\audiocpy\cwmmaudio2.dll  d:\os2\dll\CWMMAUDI.DLL g:\projects_working\audiocpy\oldMMAdll'
*/

Exit;
