
/*
 * This file was generated by the SOM Compiler.
 * FileName: include\cwgif.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 * 
 * CWgif.idl:
 */


#ifndef SOM_CWGIF_h
#define SOM_CWGIF_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef CWGIF
#define CWGIF SOMObject
#endif
#include <cwimage.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPDataFile
    #define M_WPDataFile SOMObject
#endif /* M_WPDataFile */
#ifndef M_WPImageFile
    #define M_WPImageFile SOMObject
#endif /* M_WPImageFile */
#ifndef M_CWImage
    #define M_CWImage SOMObject
#endif /* M_CWImage */
#ifndef M_CWGIF
    #define M_CWGIF SOMObject
#endif /* M_CWGIF */

/*
 * End of user-defined types.
 */

#define CWGIF_MajorVersion 1
#define CWGIF_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define CWGIFNewClass cwgifc
#pragma linkage(cwgifc, system)
#define CWGIFClassData cwgifd
#define CWGIFCClassData cwgifx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <cwgif.h>
/*--------------Migration------------*/
#define CWGIF_classObj CWGIFClassData.classObject
#define _CWGIF CWGIF_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK CWGIFNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(CWGIFNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct CWGIFClassDataStructure {
	SOMClass *classObject;
} SOMDLINK CWGIFClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct CWGIFCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK CWGIFCClassData;

/*
 * New and Renew macros for CWGIF
 */
#define CWGIFNew() \
   (_somNew(_CWGIF ? _CWGIF : CWGIFNewClass(CWGIF_MajorVersion, CWGIF_MinorVersion)))
#define CWGIFRenew(buf) \
   (_somRenew(_CWGIF ? _CWGIF : CWGIFNewClass(CWGIF_MajorVersion, CWGIF_MinorVersion), buf))
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define CWGIF_cwmmAddImageInformationPage CWImage_cwmmAddImageInformationPage
#define CWGIF_wpQueryBitmapHandle WPImageFile_wpQueryBitmapHandle
#define CWGIF_wpQueryBitmapInfoHeader WPImageFile_wpQueryBitmapInfoHeader
#define CWGIF_wpQueryBitmapData WPImageFile_wpQueryBitmapData
#define CWGIF_wpSetBitmapData WPImageFile_wpSetBitmapData
#define CWGIF_wpReadImageFile WPImageFile_wpReadImageFile
#define CWGIF_wpWriteImageFile WPImageFile_wpWriteImageFile
#define CWGIF_wpAddFileTypePage WPDataFile_wpAddFileTypePage
#define CWGIF_wpPrintMetaFile WPDataFile_wpPrintMetaFile
#define CWGIF_wpPrintPifFile WPDataFile_wpPrintPifFile
#define CWGIF_wpPrintPrinterSpecificFile WPDataFile_wpPrintPrinterSpecificFile
#define CWGIF_wpPrintUnknownFile WPDataFile_wpPrintUnknownFile
#define CWGIF_wpQueryAssociatedProgram WPDataFile_wpQueryAssociatedProgram
#define CWGIF_wpSetAssociatedFileIcon WPDataFile_wpSetAssociatedFileIcon
#define CWGIF_wpQueryAssociatedFileIcon WPDataFile_wpQueryAssociatedFileIcon
#define CWGIF_wpSetRealName WPFileSystem_wpSetRealName
#define CWGIF_wpSetType WPFileSystem_wpSetType
#define CWGIF_wpQueryType WPFileSystem_wpQueryType
#define CWGIF_wpSetAttr WPFileSystem_wpSetAttr
#define CWGIF_wpQueryAttr WPFileSystem_wpQueryAttr
#define CWGIF_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define CWGIF_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define CWGIF_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define CWGIF_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define CWGIF_wpQueryCreation WPFileSystem_wpQueryCreation
#define CWGIF_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define CWGIF_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define CWGIF_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define CWGIF_wpQueryEASize WPFileSystem_wpQueryEASize
#define CWGIF_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define CWGIF_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define CWGIF_wpRefresh WPFileSystem_wpRefresh
#define CWGIF_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define CWGIF_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define CWGIF_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define CWGIF_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define CWGIF_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define CWGIF_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define CWGIF_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define CWGIF_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define CWGIF_wpQueryRealName WPFileSystem_wpQueryRealName
#define CWGIF_wpQueryFilename WPFileSystem_wpQueryFilename
#define CWGIF_wpQueryDisk WPFileSystem_wpQueryDisk
#define CWGIF_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define CWGIF_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define CWGIF_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define CWGIF_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define CWGIF_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define CWGIF_wpAddSettingsPages WPObject_wpAddSettingsPages
#define CWGIF_wpAddToObjUseList WPObject_wpAddToObjUseList
#define CWGIF_wpAllocMem WPObject_wpAllocMem
#define CWGIF_wpAppendObject WPObject_wpAppendObject
#define CWGIF_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define CWGIF_wpClose WPObject_wpClose
#define CWGIF_wpCnrInsertObject WPObject_wpCnrInsertObject
#define CWGIF_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define CWGIF_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define CWGIF_wpConfirmDelete WPObject_wpConfirmDelete
#define CWGIF_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define CWGIF_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define CWGIF_wpCopyObject WPObject_wpCopyObject
#define CWGIF_wpCreateAnother WPObject_wpCreateAnother
#define CWGIF_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define CWGIF_wpCreateShadowObject WPObject_wpCreateShadowObject
#define CWGIF_wpDelete WPObject_wpDelete
#define CWGIF_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define CWGIF_wpDisplayHelp WPObject_wpDisplayHelp
#define CWGIF_wpDisplayMenu WPObject_wpDisplayMenu
#define CWGIF_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define CWGIF_wpDraggedOverObject WPObject_wpDraggedOverObject
#define CWGIF_wpDragOver WPObject_wpDragOver
#define CWGIF_wpDrop WPObject_wpDrop
#define CWGIF_wpDroppedOnObject WPObject_wpDroppedOnObject
#define CWGIF_wpEndConversation WPObject_wpEndConversation
#define CWGIF_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define CWGIF_wpFindUseItem WPObject_wpFindUseItem
#define CWGIF_wpFormatDragItem WPObject_wpFormatDragItem
#define CWGIF_wpFree WPObject_wpFree
#define CWGIF_wpFreeMem WPObject_wpFreeMem
#define CWGIF_wpHide WPObject_wpHide
#define CWGIF_wpInitData WPObject_wpInitData
#define CWGIF_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define CWGIF_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define CWGIF_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define CWGIF_wpMenuItemSelected WPObject_wpMenuItemSelected
#define CWGIF_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define CWGIF_wpMoveObject WPObject_wpMoveObject
#define CWGIF_wpOpen WPObject_wpOpen
#define CWGIF_wpPrintObject WPObject_wpPrintObject
#define CWGIF_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define CWGIF_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define CWGIF_wpQueryConfirmations WPObject_wpQueryConfirmations
#define CWGIF_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define CWGIF_wpQueryDefaultView WPObject_wpQueryDefaultView
#define CWGIF_wpQueryDetailsData WPObject_wpQueryDetailsData
#define CWGIF_wpQueryError WPObject_wpQueryError
#define CWGIF_wpSetFolder WPObject_wpSetFolder
#define CWGIF_wpQueryFolder WPObject_wpQueryFolder
#define CWGIF_wpQueryIcon WPObject_wpQueryIcon
#define CWGIF_wpQueryIconData WPObject_wpQueryIconData
#define CWGIF_wpQueryMinWindow WPObject_wpQueryMinWindow
#define CWGIF_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define CWGIF_wpQueryStyle WPObject_wpQueryStyle
#define CWGIF_wpSetTaskRec WPObject_wpSetTaskRec
#define CWGIF_wpFindTaskRec WPObject_wpFindTaskRec
#define CWGIF_wpQueryTitle WPObject_wpQueryTitle
#define CWGIF_wpRegisterView WPObject_wpRegisterView
#define CWGIF_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define CWGIF_wpRender WPObject_wpRender
#define CWGIF_wpRenderComplete WPObject_wpRenderComplete
#define CWGIF_wpReplaceObject WPObject_wpReplaceObject
#define CWGIF_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define CWGIF_wpRestore WPObject_wpRestore
#define CWGIF_wpRestoreData WPObject_wpRestoreData
#define CWGIF_wpRestoreLong WPObject_wpRestoreLong
#define CWGIF_wpRestoreState WPObject_wpRestoreState
#define CWGIF_wpRestoreString WPObject_wpRestoreString
#define CWGIF_wpSaveData WPObject_wpSaveData
#define CWGIF_wpSaveImmediate WPObject_wpSaveImmediate
#define CWGIF_wpSaveDeferred WPObject_wpSaveDeferred
#define CWGIF_wpSaveLong WPObject_wpSaveLong
#define CWGIF_wpSaveState WPObject_wpSaveState
#define CWGIF_wpSaveString WPObject_wpSaveString
#define CWGIF_wpScanSetupString WPObject_wpScanSetupString
#define CWGIF_wpSetConcurrentView WPObject_wpSetConcurrentView
#define CWGIF_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define CWGIF_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define CWGIF_wpSetDefaultView WPObject_wpSetDefaultView
#define CWGIF_wpSetError WPObject_wpSetError
#define CWGIF_wpSetIconHandle WPObject_wpSetIconHandle
#define CWGIF_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define CWGIF_wpSetupOnce WPObject_wpSetupOnce
#define CWGIF_wpSetIcon WPObject_wpSetIcon
#define CWGIF_wpSetIconData WPObject_wpSetIconData
#define CWGIF_wpSetMinWindow WPObject_wpSetMinWindow
#define CWGIF_wpSetStyle WPObject_wpSetStyle
#define CWGIF_wpModifyStyle WPObject_wpModifyStyle
#define CWGIF_wpSetTitle WPObject_wpSetTitle
#define CWGIF_wpSetup WPObject_wpSetup
#define CWGIF_wpSwitchTo WPObject_wpSwitchTo
#define CWGIF_wpUnInitData WPObject_wpUnInitData
#define CWGIF_wpViewObject WPObject_wpViewObject
#define CWGIF_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define CWGIF_wpQueryHandle WPObject_wpQueryHandle
#define CWGIF_wpUnlockObject WPObject_wpUnlockObject
#define CWGIF_wpObjectReady WPObject_wpObjectReady
#define CWGIF_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define CWGIF_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define CWGIF_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define CWGIF_wpIsDeleteable WPObject_wpIsDeleteable
#define CWGIF_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define CWGIF_wpSetObjectID WPObject_wpSetObjectID
#define CWGIF_wpQueryObjectID WPObject_wpQueryObjectID
#define CWGIF_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define CWGIF_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define CWGIF_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define CWGIF_wpFindViewItem WPObject_wpFindViewItem
#define CWGIF_wpLockObject WPObject_wpLockObject
#define CWGIF_wpIsLocked WPObject_wpIsLocked
#define CWGIF_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define CWGIF_wpWaitForClose WPObject_wpWaitForClose
#define CWGIF_somDefaultInit SOMObject_somDefaultInit
#define CWGIF_somDestruct SOMObject_somDestruct
#define CWGIF_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define CWGIF_somDefaultAssign SOMObject_somDefaultAssign
#define CWGIF_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define CWGIF_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define CWGIF_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define CWGIF_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define CWGIF_somDefaultVAssign SOMObject_somDefaultVAssign
#define CWGIF_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define CWGIF_somInit SOMObject_somInit
#define CWGIF_somFree SOMObject_somFree
#define CWGIF_somUninit SOMObject_somUninit
#define CWGIF_somGetClass SOMObject_somGetClass
#define CWGIF_somGetClassName SOMObject_somGetClassName
#define CWGIF_somGetSize SOMObject_somGetSize
#define CWGIF_somIsA SOMObject_somIsA
#define CWGIF_somIsInstanceOf SOMObject_somIsInstanceOf
#define CWGIF_somRespondsTo SOMObject_somRespondsTo
#define CWGIF_somDispatch SOMObject_somDispatch
#define CWGIF_somClassDispatch SOMObject_somClassDispatch
#define CWGIF_somCastObj SOMObject_somCastObj
#define CWGIF_somResetObj SOMObject_somResetObj
#define CWGIF_somDispatchV SOMObject_somDispatchV
#define CWGIF_somDispatchL SOMObject_somDispatchL
#define CWGIF_somDispatchA SOMObject_somDispatchA
#define CWGIF_somDispatchD SOMObject_somDispatchD
#define CWGIF_somPrintSelf SOMObject_somPrintSelf
#define CWGIF_somDumpSelf SOMObject_somDumpSelf
#define CWGIF_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_CWGIF_h */

#ifndef SOM_M_CWGIF_h
#define SOM_M_CWGIF_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_CWGIF
#define M_CWGIF SOMObject
#endif
#include <cwimage.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_CWGIF_MajorVersion 1
#define M_CWGIF_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_CWGIFNewClass cwgifMc
#pragma linkage(cwgifMc, system)
#define M_CWGIFClassData cwgifMd
#define M_CWGIFCClassData cwgifMx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_CWGIF_classObj M_CWGIFClassData.classObject
#define _M_CWGIF M_CWGIF_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_CWGIFNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_CWGIFNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_CWGIFClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_CWGIFClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_CWGIFCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_CWGIFCClassData;

/*
 * New and Renew macros for M_CWGIF
 */
#define M_CWGIFNew() \
   (_somNew(_M_CWGIF ? _M_CWGIF : M_CWGIFNewClass(M_CWGIF_MajorVersion, M_CWGIF_MinorVersion)))
#define M_CWGIFRenew(buf) \
   (_somRenew(_M_CWGIF ? _M_CWGIF : M_CWGIFNewClass(M_CWGIF_MajorVersion, M_CWGIF_MinorVersion), buf))

/*
 * Override method: wpclsQueryInstanceType
 */
#define M_CWGIF_wpclsQueryInstanceType(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceType(somSelf)

/*
 * Override method: wpclsQueryInstanceFilter
 */
#define M_CWGIF_wpclsQueryInstanceFilter(somSelf) \
	M_WPFileSystem_wpclsQueryInstanceFilter(somSelf)

/*
 * Override method: wpclsQueryDefaultHelp
 */
#define M_CWGIF_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary) \
	M_WPObject_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary)

/*
 * Override method: wpclsQueryStyle
 */
#define M_CWGIF_wpclsQueryStyle(somSelf) \
	M_WPObject_wpclsQueryStyle(somSelf)

/*
 * Override method: wpclsQueryTitle
 */
#define M_CWGIF_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_CWGIF_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_CWGIF_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_CWGIF_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_CWGIF_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_CWGIF_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_CWGIF_wpclsInitData M_WPObject_wpclsInitData
#define M_CWGIF_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_CWGIF_wpclsNew M_WPObject_wpclsNew
#define M_CWGIF_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_CWGIF_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_CWGIF_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_CWGIF_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_CWGIF_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_CWGIF_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_CWGIF_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_CWGIF_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_CWGIF_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_CWGIF_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_CWGIF_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_CWGIF_wpclsSetError M_WPObject_wpclsSetError
#define M_CWGIF_wpclsQueryError M_WPObject_wpclsQueryError
#define M_CWGIF_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_CWGIF_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_CWGIF_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_CWGIF_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_CWGIF_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_CWGIF_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_CWGIF_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_CWGIF_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_CWGIF_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_CWGIF_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_CWGIF_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_CWGIF_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_CWGIF__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_CWGIF__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_CWGIF__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_CWGIF__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_CWGIF_somNew SOMClass_somNew
#define M_CWGIF_somNewNoInit SOMClass_somNewNoInit
#define M_CWGIF_somRenew SOMClass_somRenew
#define M_CWGIF_somRenewNoInit SOMClass_somRenewNoInit
#define M_CWGIF_somRenewNoZero SOMClass_somRenewNoZero
#define M_CWGIF_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_CWGIF_somAllocate SOMClass_somAllocate
#define M_CWGIF_somDeallocate SOMClass_somDeallocate
#define M_CWGIF__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_CWGIF__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_CWGIF_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_CWGIF_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_CWGIF_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_CWGIF_somInitClass SOMClass_somInitClass
#define M_CWGIF_somInitMIClass SOMClass_somInitMIClass
#define M_CWGIF_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_CWGIF_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_CWGIF_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_CWGIF_somClassReady SOMClass_somClassReady
#define M_CWGIF_somGetApplyStub SOMClass_somGetApplyStub
#define M_CWGIF_somGetClassData SOMClass_somGetClassData
#define M_CWGIF_somSetClassData SOMClass_somSetClassData
#define M_CWGIF_somGetClassMtab SOMClass_somGetClassMtab
#define M_CWGIF_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_CWGIF_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_CWGIF_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_CWGIF_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_CWGIF_somGetMemberToken SOMClass_somGetMemberToken
#define M_CWGIF_somGetMethodData SOMClass_somGetMethodData
#define M_CWGIF_somGetRdStub SOMClass_somGetRdStub
#define M_CWGIF_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_CWGIF_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_CWGIF_somGetMethodToken SOMClass_somGetMethodToken
#define M_CWGIF_somGetName SOMClass_somGetName
#define M_CWGIF_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_CWGIF_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_CWGIF_somGetNumMethods SOMClass_somGetNumMethods
#define M_CWGIF_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_CWGIF_somGetParent SOMClass_somGetParent
#define M_CWGIF_somGetParents SOMClass_somGetParents
#define M_CWGIF_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_CWGIF_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_CWGIF_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_CWGIF_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_CWGIF_somFindMethod SOMClass_somFindMethod
#define M_CWGIF_somFindMethodOk SOMClass_somFindMethodOk
#define M_CWGIF_somFindSMethod SOMClass_somFindSMethod
#define M_CWGIF_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_CWGIF_somLookupMethod SOMClass_somLookupMethod
#define M_CWGIF_somCheckVersion SOMClass_somCheckVersion
#define M_CWGIF_somDescendedFrom SOMClass_somDescendedFrom
#define M_CWGIF_somSupportsMethod SOMClass_somSupportsMethod
#define M_CWGIF_somDefinedMethod SOMClass_somDefinedMethod
#define M_CWGIF_somOverrideMtab SOMClass_somOverrideMtab
#define M_CWGIF_somDefaultInit SOMObject_somDefaultInit
#define M_CWGIF_somDestruct SOMObject_somDestruct
#define M_CWGIF_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_CWGIF_somDefaultAssign SOMObject_somDefaultAssign
#define M_CWGIF_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_CWGIF_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_CWGIF_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_CWGIF_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_CWGIF_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_CWGIF_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_CWGIF_somInit SOMObject_somInit
#define M_CWGIF_somFree SOMObject_somFree
#define M_CWGIF_somUninit SOMObject_somUninit
#define M_CWGIF_somGetClass SOMObject_somGetClass
#define M_CWGIF_somGetClassName SOMObject_somGetClassName
#define M_CWGIF_somGetSize SOMObject_somGetSize
#define M_CWGIF_somIsA SOMObject_somIsA
#define M_CWGIF_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_CWGIF_somRespondsTo SOMObject_somRespondsTo
#define M_CWGIF_somDispatch SOMObject_somDispatch
#define M_CWGIF_somClassDispatch SOMObject_somClassDispatch
#define M_CWGIF_somCastObj SOMObject_somCastObj
#define M_CWGIF_somResetObj SOMObject_somResetObj
#define M_CWGIF_somDispatchV SOMObject_somDispatchV
#define M_CWGIF_somDispatchL SOMObject_somDispatchL
#define M_CWGIF_somDispatchA SOMObject_somDispatchA
#define M_CWGIF_somDispatchD SOMObject_somDispatchD
#define M_CWGIF_somPrintSelf SOMObject_somPrintSelf
#define M_CWGIF_somDumpSelf SOMObject_somDumpSelf
#define M_CWGIF_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_CWGIF_h */
